homeassistant:
  name: "Home"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  external_url: !secret external_url
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - /tmp

config:

api:

scene: !include scenes.yaml

logger: !include config/logger.yaml

http: !include config/http.yaml

frontend: !include config/frontend.yaml

lovelace: !include config/lovelace.yaml

influxdb: !include config/influxdb.yaml

ios:

mobile_app:

notify: !include config/notify.yaml

google_assistant: !include config/google_assistant.yaml

panel_custom: !include config/panel_custom.yaml

system_health:

sun: