homeassistant:
  name: "Home"
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  external_url: !secret external_url
  packages: !include_dir_named packages/
  allowlist_external_dirs:
    - /tmp

scene: !include scenes.yaml
script: !include scripts.yaml


# Configuration

config:

backup:

frontend: !include config/frontend.yaml

google_assistant: !include config/google_assistant.yaml

http: !include config/http.yaml

influxdb: !include config/influxdb.yaml

logger: !include config/logger.yaml

lovelace: !include config/lovelace.yaml

media_source:

notify: !include config/notify.yaml

panel_custom: !include config/panel_custom.yaml

tts: !include config/tts.yaml


# Add ons

api:

mobile_app:

ios:
