config:

api:

logger: !include config/logger.yaml

alexa: !include config/alexa.yaml

http: !include config/http.yaml

frontend: !include config/frontend.yaml

lovelace: !include config/lovelace.yaml

influxdb: !include config/influxdb.yaml

notify: !include config/notify.yaml

zwave: !include config/zwave.yaml

script: !include packages/scripts.yaml

system_health:

sun:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: !secret units
  time_zone: !secret time_zone
  packages:
    climate: !include packages/climate.yaml
    energy: !include packages/energy.yaml
    landscaping: !include packages/landscaping.yaml
    lights: !include packages/lights.yaml
    media: !include packages/media.yaml
    network: !include packages/network.yaml
    scenes: !include packages/scenes.yaml
    security: !include packages/security.yaml
    settings: !include packages/settings.yaml
    system: !include packages/system.yaml
    weather: !include packages/weather.yaml
  whitelist_external_dirs:
    - /tmp