kiosk_mode:
  hide_header: true
  hide_sidebar: true
  admin_settings:
    hide_sidebar: false


views:
  - path: "home"
    cards:
      - type: vertical-stack
        cards:
          # Header and alarm
          - type: entity
            name: "Home"
            entity: alarm_control_panel.alarm
            card_mod:
              style: |
                :host ha-card {
                  background: none;
                  border: 0;
                }

                :host ha-card .header {
                  padding: 0 0 0 5px;
                }

                :host ha-card .name {
                  color: var(--primary-text-color);
                  font-size: 24px;
                  font-weight: 400;
                }

                :host ha-card .info {
                  position: absolute;
                  top: 10px;
                  right: 10px;
                }

                :host ha-card .value {
                  font-size: 16px;
                  font-weight: 500;
                }
          
          # Status  
          - type: markdown
            entity_id:
              - sensor.outdoor_forecast
              - sensor.outside_temp
              - sensor.outside_rain_daily
            content: |
              {%- if states('sensor.outside_temp') -%}
                <ha-icon icon="mdi:weather-rainy"></ha-icon> Currently {{ states('sensor.outside_temp')|round(0, default=0) }}°F&nbsp; 

                {%- if states('sensor.outside_rain_daily')|float(0) -%}
                  with {{ states('sensor.outside_rain_daily') }}" of rain
                {%- else -%}
                  {{ states('sensor.outdoor_forecast') }}
                {%- endif -%}
              {%- endif -%}
            card_mod:
              style: |
                :host ha-card { 
                  background: none;
                  border: 0;
                  margin: -5px 0 5px -10px;
                  color: var(--secondary-text-color);
                }

          # Camera
          - type: picture-entity
            entity: camera.front_patio
            show_name: false
            show_state: false
            tap_action: 
              action: 'navigate'
              navigation_path: '/lovelace-views/cameras'
            card_mod:
              style: |
                :host ha-card { 
                  margin: 0 -8px 3px;
                  border: 0;
                  border-radius: 0;
                }
                
          # Buttons
          - type: horizontal-stack
            cards:
              # Dinner
              - name: "Dinner" 
                entity: script.dinner_lights
                tap_action:
                  action: call-service
                  service: script.dinner_lights
                icon: mdi:pot-steam
                <<: &buttons
                  type: entity-button
                  icon_height: 25px
                  card_mod:
                    style: |
                      :host ha-card {  
                        height: auto;
                        border: 0;
                        border-radius: 6px;
                        margin-bottom: 30px;
                        font-size: 14px;
                        font-weight: 500;
                      }
                      
              # Mood
              - name: "Mood" 
                entity: script.mood_lights
                tap_action:
                  action: call-service
                  service: script.mood_lights
                icon: mdi:movie-filter
                <<: *buttons


          # Navigation
          - type: entities
            entities:
              - name: "Family Rooms"
                type: weblink
                url: "/lovelace-views/family_rooms"
                icon: "mdi:chevron-right-circle"
            <<: &nav_link_style
              card_mod:
                style:
                  hui-weblink-row: 
                    $: |
                      a {
                        text-decoration: none;
                        color: var(--primary-text-color) !important;
                        font-size: 24px;
                      }

                      a div {
                        margin-left: 10px;
                      }

                  .: |
                    ha-card {
                      padding: 0;
                      background: none;
                      border: 0;
                      z-index: 1;

                    }

                    #states {
                      padding: 0;
                      margin: -10px 0 0;
                    }

          - type: markdown
            entity_id:
              - lights.living_area
            content: >
              {{ expand('light.living_area') | selectattr('state', 'eq', 'on') | list | count }} lights on. 
              The temperature is {{ states('sensor.family_room_temperature') }}°F.
              Windows are open.
            <<: &nav_secondary_style
              card_mod:
                  style: |
                    :host ha-card { 
                      background: none;
                      border: 0;
                      margin: -27px 0 20px 50px;
                      color: var(--secondary-text-color)
                    }

                    :host ha-markdown {
                      padding: 0;
                    }

          - type: entities
            entities:
              - name: "Kitchen"
                type: weblink 
                url: "/lovelace-views/kitchen"
                icon: "mdi:chevron-right-circle"
            <<: *nav_link_style

          - type: markdown
            entity_id:
              - lights.kitchen_area
            content: >
              {{ expand('light.living_area') | selectattr('state', 'eq', 'on') | list | count }} lights on. 
              Windows are open.
            <<: *nav_secondary_style

          - type: entities
            entities:
              - name: "Bedrooms" 
                type: weblink
                url: "/lovelace-views/bedrooms"
                icon: "mdi:chevron-right-circle"
            <<: *nav_link_style

          - type: markdown
            entity_id:
              - lights.bedroom_area
            content: >
              {{ expand('light.bedroom_area') | selectattr('state', 'eq', 'on') | list | count }} lights on. 
              The temperature is {{ states('sensor.family_room_temperature') }}°F.
              Windows are open.
            <<: *nav_secondary_style

          - type: entities
            entities:
              - name: "Outside"
                type: weblink
                url: "/lovelace-views/outside"
                icon: "mdi:chevron-right-circle"
            <<: *nav_link_style

          - type: markdown
            entity_id:
              - lights.outside
            content: >
              {{ expand('light.outside') | selectattr('state', 'eq', 'on') | list | count }} lights on. 
              Garages are open.
            <<: *nav_secondary_style
