title: Home

custom_header:
  compact_mode: true
  menu_dropdown: true
  hide_help: true
  hide_unused: true
  hide_config: true
  footer_mode: true
  tab_indicator_color: transparent
  header_css: "height: 90px;"

resources:
  - type: module
    url: /local/community/custom-header/custom-header.js

views:
  - title: "Home"
    cards:

      - type: vertical-stack
        title: Home
        cards:
          - type: markdown
            content: >-
              Currently {{ states('sensor.outside_temp')|round(0) }}°F
              {% if states('sensor.outside_rain_daily')|float > 0 %} with {{ states('sensor.outside_rain_daily') }}" of rain{% endif %}.
              {{ states('sensor.outdoor_forecast') }}

          - type: picture
            image: /local/photos/house.jpg

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "armed_home"
            card:
              type: horizontal-stack
              title: Scenes
              cards:
                - type: entity-button
                  entity: script.alarm_disarm_silently
                  name: Let Dog Out
                  icon: mdi:dog-side
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: script.alarm_disarm_silently

                - type: entity-button
                  entity: scene.good_morning
                  name: Good Morning
                  icon: mdi:brightness-5
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.good_morning

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              title: Scenes
              cards:
                - type: entity-button
                  entity: scene.dinner_time
                  name: Dinner Lights
                  icon: mdi:food-variant
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.dinner_time

                - type: entity-button
                  entity: scene.movie_time
                  name: Movie Lights
                  icon: mdi:movie
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.movie_time

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: scene.good_night
                  name: Good Night
                  icon: mdi:brightness-2
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.good_night

                - type: entity-button
                  entity: scene.i_m_leaving
                  name: I'm Leaving
                  icon: mdi:exit-run
                  icon_height: 2em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.i_m_leaving

          - type: vertical-stack
            title: "Security"
            cards:
              - type: markdown
                content: >
                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}
                    Alarm is armed home.
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}
                    Alarm is armed away.
                  {% else %}
                    Alarm is disarmed.
                  {% endif %}

              - type: entity-filter
                card:
                  type: entities
                  show_header_toggle: false
                state_filter:
                  - "on"
                show_empty: false
                entities:
                  - entity: binary_sensor.front_door
                    icon: mdi:door
                  - entity: binary_sensor.family_room_doors
                    icon: mdi:door
                  - entity: binary_sensor.dining_room_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.living_room_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.living_room_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.kitchen_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.masons_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.brinks_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.guest_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_bedroom_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_bedroom_doors
                    icon: mdi:door
                  - entity: binary_sensor.laundry_room_door
                    icon: mdi:door
                  - entity: binary_sensor.jeffs_garage_door
                    icon: mdi:garage
                  - entity: binary_sensor.jillians_garage_door
                    icon: mdi:garage
                  - entity: binary_sensor.guest_garage_door
                    icon: mdi:garage


  - title: "Rooms"
    cards:
      - type: entities
        title: "Kitchen"
        show_header_toggle: false
        entities:
          - entity: light.kitchen
            name: Lights
          - entity: switch.kitchen_cabinets
            icon: mdi:lightbulb
          - entity: light.island
          - entity: light.pantry

      - type: entities
        title: "Family Room"
        show_header_toggle: false
        entities:
          - entity: sensor.family_room_status
          - type: picture-entity
            entity: camera.family_room
          - entity: light.family_room
            name: "Lights"
          - entity: sensor.family_room_media
            name: "TV"
            icon: mdi:television
          - entity: input_select.family_room_media
            icon: mdi:remote

      - type: conditional
        conditions:
          - entity: sensor.family_room_media
            state: "Speakers"
        card:
          type: entities
          entities:
            - entity: script.back_yard_speakers_on
              name: "Play Outside"
              icon: mdi:speaker

      - type: entities
        title: "Living Room"
        show_header_toggle: false
        entities:
          - entity: sensor.living_room_status
          - entity: switch.living_room
            name: Lights
            icon: mdi:lightbulb
          - entity: light.dining_room

      - type: entities
        title: "Entryway"
        show_header_toggle: false
        entities:
          - entity: switch.entryway
            name: Chandelier
            icon: mdi:lightbulb
          - entity: switch.hallway
            icon: mdi:lightbulb
          - entity: sensor.climate_mode
            name: "HVAC"
          - entity: switch.house_fan_switch
            icon: mdi:fan

      - type: entities
        title: "Boys' Bedroom"
        show_header_toggle: false
        entities:
          - entity: sensor.boys_bedroom_status
          - entity: switch.boys_bedroom
            name: Light
            icon: mdi:lightbulb

      - type: entities
        title: "Master Bedroom"
        show_header_toggle: false
        entities:
          - entity: sensor.master_bedroom_status
          - entity: light.master_bedroom
            name: Light

      - type: entities
        title: "Play Room"
        show_header_toggle: false
        entities:
          - entity: sensor.playroom_status
          - entity: light.play_room
            name: Light

      - type: entities
        title: "Guest Bedroom"
        show_header_toggle: false
        entities:
          - entity: sensor.guest_bedroom_status
          - entity: light.guest_bedroom
            name: Light


  - title: "Outside"
    cards:
      - type: entities
        title: "Landscape"
        show_header_toggle: false
        entities:
          - entity: switch.front_yard_switch
            icon: mdi:lightbulb
          - entity: switch.back_yard_switch
            icon: mdi:lightbulb
          - entity: switch.front_landscape
            icon: mdi:flower-tulip
          - entity: switch.back_landscape
            icon: mdi:flower-tulip
          - entity: switch.pool_light
            icon: mdi:pool
          - entity: switch.fountain
            icon: mdi:cup-water
          - entity: automation.landscape_fountain
            name: "Automate Fountain"
