title: "Home"

views:
  - title: "Home"
    path: "home"
    cards:
      - type: vertical-stack
        title: "Home"
        cards:
          # House Pic
          - type: picture-entity
            entity: camera.front_door
            show_name: false
            show_state: false
            tap_action: 
              action: 'navigate'
              navigation_path: '/lovelace/cameras'
            card_mod:
              style: |
                .type-picture-entity {
                  background-color: rgb(85, 85, 85);
                  border-radius: var(--ha-card-border-radius, 4px);
                  min-height: 280px;
                  transition: none;
                }

                @media only screen and (hover: none) and (pointer: coarse) {
                  .type-picture-entity {
                    min-height: 215px !important;
                  }
                }

          # Actions - Alarm is on
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "armed_home"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.let_dog_out
                  name: "Let Dog Out"
                  icon: mdi:dog-side
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.let_dog_out

                - type: entity-button
                  entity: script.good_morning
                  name: "Good Morning"
                  icon: mdi:brightness-5
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.good_morning

          # Actions - Alarm is off temporarily
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: script.let_dog_out
                state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.let_dog_out
                  name: "Alarm Will Automatically Arm"
                  icon: mdi:timer
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    confirmation:
                      text: "Are you sure you want to leave the alarm off?"
                    service: script.turn_off
                    service_data:
                      entity_id: script.let_dog_out

          # Actions - Alarm is off
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: script.let_dog_out
                state_not: "on"
            card:
              type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: script.dinner_lights
                      name: "Dinner"
                      icon: mdi:food-fork-drink
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.dinner_lights
                    - type: entity-button
                      entity: script.mood_lights
                      name: "Movie"
                      icon: mdi:movie
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.mood_lights

                - type: horizontal-stack
                  cards:
                    - type: conditional
                      conditions:
                        - entity: sun.sun
                          state: "above_horizon"
                      card:
                        type: entity-button
                        entity: script.good_morning
                        name: "Good Morning"
                        icon: mdi:brightness-5
                        icon_height: 1.5em
                        tap_action:
                          action: call-service
                          service: script.good_morning
                    - type: conditional
                      conditions:
                        - entity: sun.sun
                          state_not: "above_horizon"
                      card:
                        type: entity-button
                        entity: script.good_night
                        name: "Good Night"
                        icon: mdi:brightness-2
                        icon_height: 1.5em
                        tap_action:
                          action: call-service
                          service: script.good_night
                    - type: entity-button
                      entity: script.away
                      name: "Away"
                      icon: mdi:exit-run
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.away


          - type: vertical-stack
            title: "Status"
            cards:
              - type: markdown
                entity_id:
                  - sensor.outdoor_forecast
                  - sensor.outside_temp
                  - sensor.outside_uv
                  - sensor.outside_rain_daily
                  - sensor.air_pollution_level
                  - alarm_control_panel.abode_alarm
                content: >
                  <ha-icon icon="{{ state_attr('sensor.outdoor_forecast', 'icon') }}"></ha-icon> Currently {{ states('sensor.outside_temp')|round(0, default=0) }}°F {{ states('sensor.outdoor_forecast') }}

                  {% if states('sensor.outside_uv')|int > 3 %}
                    <ha-icon icon="mdi:sun-wireless-outline"></ha-icon> UV is high so wear sunscreen!
                  {% endif %}

                  {% if states('sensor.outside_rain_daily')|float(0) %}
                    <ha-icon icon="mdi:weather-rainy"></ha-icon> It rained {{ states('sensor.outside_rain_daily') }}" today

                  {% endif %}
                  {% if states('sensor.air_pollution_level') != 'good' %}
                    <ha-icon icon="mdi:weather-fog"></ha-icon> Air quality is {{ states('sensor.air_pollution_level') }}

                  {% endif %}
                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}
                    <ha-icon icon="mdi:shield-home-outline"></ha-icon> Alarm is armed home
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}
                    <ha-icon icon="mdi:shield-lock-outline"></ha-icon> Alarm is armed away
                  {% endif %}

              - type: 'custom:auto-entities'
                card:
                  type: entities
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.doors_and_windows
                    - group: group.entrances
                  exclude:
                    - state: "off"
                    - state: "unavailable"
                show_empty: false

  - title: "Inside"
    path: "inside"
    cards:
      - type: entities
        title: "Lights"
        state_color: true
        show_header_toggle: true
        entities:
          # Family Room Area
          - type: custom:multiple-entity-row
            entity: light.family_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.family_room_temperature
                name: false
                format: 'precision0'
          - entity: light.kitchen
          - entity: switch.kitchen_cabinets
            name: "Cabinets"
            icon: mdi:lightbulb
          - entity: light.island

          - type: divider

          # Living Room Area
          - type: custom:multiple-entity-row
            entity: switch.living_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.living_room_temperature
                name: false
                format: 'precision0'
          - entity: light.dining_room
          - entity: light.entryway
          - entity: switch.hallway
            icon: mdi:lightbulb

          - type: divider

          # Bedrooms
          - type: custom:multiple-entity-row
            entity: light.master_bedroom
            toggle: true
            entities:
              - entity: sensor.master_bedroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: switch.boys_bedroom
            toggle: true
            entities:
              - entity: sensor.boys_bedroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: light.play_room
            toggle: true
            entities:
              - entity: sensor.playroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: light.guest_bedroom
            toggle: true
            entities:
              - entity: sensor.guest_bedroom_temperature
                name: false
                format: 'precision0'

      - type: entities
        title: "Media"
        state_color: true
        show_header_toggle: false
        entities:
          - entity: switch.family_room_apple_tv
            icon: mdi:television
          - entity: switch.family_room_speakers
            icon: mdi:speaker

      - type: entities
        title: "Climate"
        state_color: true
        show_header_toggle: false
        entities:
          - type: custom:multiple-entity-row
            entity: climate.home
            name: "Climate"
            show_state: false
            state_color: false
            entities:
              - attribute: current_temperature
                name: "Temperature"
                unit: "°F"
                format: 'precision0'
              - attribute: preset_mode
                name: "Mode"
          - entity: switch.house_fan_switch
            icon: mdi:fan
            name: "Fan"
          - type: section
          - entity: automation.climate_windows_open
            state_color: false
            name: "Turn off when windows open"

  - title: "Outside"
    path: "outside"

    cards:
      - type: glance
        title: "Weather"
        show_name: false
        entities:
          - entity: sensor.outside_temp
          - entity: sensor.outside_humidity
            icon: mdi:water-percent
          - entity: sensor.outside_wind_speed
            icon: mdi:weather-windy
          - entity: sensor.outside_uv
            icon: mdi:weather-sunny
      - type: entities
        title: "Garages"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: cover.garage_door_3
          - entity: cover.garage_door_2
          - entity: cover.garage_door_1
      - type: entities
        title: "Landscape"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: switch.front_yard_switch
            icon: mdi:lightbulb
          - entity: switch.back_yard_switch
            icon: mdi:lightbulb
          - entity: switch.garage_light
            icon: mdi:garage
          - entity: switch.pool_light
            icon: mdi:pool
          - entity: switch.fountain
            icon: mdi:cup-water
          - entity: switch.front_landscape
            icon: mdi:flower-tulip
          - entity: switch.back_landscape
            icon: mdi:flower-tulip

          - type: section
          - entity: automation.landscape_back_door_light
            name: "Automate Back Lights"
          - entity: automation.landscape_fountain
            name: "Automate Fountain"

  - title: "Cameras"
    path: "cameras"
    visible: false
    cards:
      - type: grid
        square: false
        columns: 2
        title: "Latest Events"
        cards:
          - type: picture-entity
            entity: camera.latest_doorbell
            name: "Doorbell"
            show_state: false
            tap_action:
              action: url
              url_path: "/local/cameras/doorbell.jpg"
            hold_action:
              action: none
          - type: picture-entity
            entity: camera.latest_mailbox
            name: "Mailbox"
            show_state: false
            tap_action:
              action: url
              url_path: "/local/cameras/mailbox.jpg"
            hold_action:
              action: none
      - type: grid
        square: false
        columns: 1
        title: "Live Cameras"
        cards:
          - type: picture-entity
            entity: camera.front_door
            show_state: false
            show_name: false
          - type: picture-entity
            entity: camera.driveway
            show_state: false
            show_name: false
          - type: picture-entity
            entity: camera.family_room
            show_state: false
            show_name: false
          - type: picture-entity
            entity: camera.living_room
            show_state: false
            show_name: false
          - type: picture-entity
            entity: camera.back_yard
            show_state: false
            show_name: false