title: Home

custom_header:
  menu_dropdown: true
  hide_help: true
  hide_unused: true
  hide_config: true
  tab_indicator_color: "transparent"
  exceptions:
    - conditions:
        user_agent: "Mobile"
      config:
        compact_mode: true
        footer_mode: true
        header_css: "height: 90px;"


views:
  - title: "Home"
    cards:

      - type: vertical-stack
        title: "Home"
        cards:
          - type: picture
            image: /local/photos/house.jpg

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "armed_home"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.alarm_disarm_silently
                  name: "Let Dog Out"
                  icon: mdi:dog-side
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.alarm_disarm_silently

                - type: entity-button
                  entity: script.good_morning
                  name: "Good Morning"
                  icon: mdi:brightness-5
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.turn_on
                    service_data:
                      entity_id: script.good_morning

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: scene.dinner_time
                  name: "Dinner"
                  icon: mdi:food-fork-drink
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.dinner_time

                - type: entity-button
                  entity: scene.movie_time
                  name: "Movie"
                  icon: mdi:movie
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.movie_time

          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: scene.good_night
                  name: "Good Night"
                  icon: mdi:brightness-2
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.good_night

                - type: entity-button
                  entity: scene.away
                  name: "Away"
                  icon: mdi:exit-run
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: scene.turn_on
                    service_data:
                      entity_id: scene.away


          - type: vertical-stack
            title: "Status"
            cards:
              - type: markdown
                content: >
                  <ha-icon icon="{{ state_attr('sensor.outdoor_forecast', 'icon') }}"></ha-icon> Outside {{ states('sensor.outside_temp')|round(0) }}°F. {{ states('sensor.outdoor_forecast') }}

                  {% if states('sensor.outside_rain_daily')|float > 0 %}
                    <ha-icon icon="mdi:weather-rainy"></ha-icon> It rained {{ states('sensor.outside_rain_daily') }}" today

                  {% endif %}
                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}
                    <ha-icon icon="mdi:shield-home-outline"></ha-icon> Alarm is armed home
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}
                    <ha-icon icon="mdi:shield-lock-outline"></ha-icon> Alarm is armed away
                  {% endif %}

              - type: entity-filter
                card:
                  type: entities
                  show_header_toggle: false
                state_filter:
                  - "on"
                show_empty: false
                entities:
                  - entity: binary_sensor.front_door
                    icon: mdi:door
                  - entity: binary_sensor.family_room_doors
                    icon: mdi:door
                  - entity: binary_sensor.dining_room_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.living_room_window_left
                    icon: mdi:window-closed
                  - entity: binary_sensor.living_room_window_right
                    icon: mdi:window-closed
                  - entity: binary_sensor.kitchen_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.boys_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.playroom_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.guest_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_bedroom_window
                    icon: mdi:window-closed
                  - entity: binary_sensor.master_bedroom_doors
                    icon: mdi:door
                  - entity: binary_sensor.laundry_room_door
                    icon: mdi:door
                  - entity: binary_sensor.jeffs_garage_door
                    icon: mdi:garage
                  - entity: binary_sensor.jillians_garage_door
                    icon: mdi:garage
                  - entity: binary_sensor.guest_garage_door
                    icon: mdi:garage


  - title: "Inside"
    cards:
      - type: entities
        title: "Lights"
        state_color: true
        show_header_toggle: true
        entities:
          - entity: light.family_room
          - entity: light.kitchen
          - entity: switch.kitchen_cabinets
            name: "Cabinets"
            icon: mdi:lightbulb
          - entity: light.island
          - entity: switch.living_room
            icon: mdi:lightbulb
          - entity: light.dining_room
          - entity: switch.entryway
            icon: mdi:lightbulb
          - entity: switch.hallway
            icon: mdi:lightbulb
          - type: custom:multiple-entity-row
            entity: light.master_bedroom
            toggle: true
            entities:
              - entity: sensor.master_bedroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: switch.boys_bedroom
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.boys_bedroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: light.play_room
            toggle: true
            entities:
              - entity: sensor.playroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: light.guest_bedroom
            toggle: true
            entities:
              - entity: sensor.guest_bedroom_status
                name: false

      - type: entities
        title: "Climate"
        state_color: true
        show_header_toggle: false
        entities:
          - type: custom:multiple-entity-row
            entity: climate.home
            name: "Climate"
            show_state: false
            state_color: false
            entities:
              - attribute: current_temperature
                name: "Temperature"
                unit: "°F"
              - entity: climate.home
                name: "Mode"
          - entity: switch.house_fan_switch
            icon: mdi:fan
            name: "Fan"

      - type: entities
        title: "Media"
        state_color: true
        show_header_toggle: false
        entities:
          - entity: sensor.family_room_media
            icon: mdi:television
            name: "Family Room"
          - entity: input_select.family_room_media
            name: "Input"

  - title: "Outside"
    cards:
      - type: entities
        title: "Weather"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: sensor.outside_temp
            name: "Temperature"
          - entity: sensor.outside_humidity
            name: "Humidity"
            icon: mdi:water-percent
          - entity: sensor.outside_uv
            name: "UV"
            icon: mdi:weather-sunny
          - entity: sensor.outside_wind_speed
            name: "Wind"
            icon: mdi:weather-windy
      - type: entities
        title: "Landscape"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: switch.front_yard_switch
            icon: mdi:lightbulb
          - entity: switch.back_yard_switch
            icon: mdi:lightbulb
          - entity: switch.front_landscape
            icon: mdi:flower-tulip
          - entity: switch.back_landscape
            icon: mdi:flower-tulip
          - entity: switch.pool_light
            icon: mdi:pool
          - entity: switch.fountain
            icon: mdi:cup-water

          - type: section
          - entity: automation.landscape_fountain
            name: "Automate Fountain"
            icon: mdi:timer
          - entity: script.back_yard_speakers_on
            name: "Play Outside"
            icon: mdi:speaker
