title: "Home"

views:
  - title: "Home"
    cards:

      - type: vertical-stack
        title: "Home"
        cards:
          # House Pic
          - type: picture-entity
            entity: camera.front_door
            show_name: false
            show_state: false
            tap_action: 
              action: 'navigate'
              navigation_path: '/lovelace-cameras/0'
            card_mod:
              style: |
                .type-picture-entity {
                  background-color: rgb(85, 85, 85);
                  border-radius: var(--ha-card-border-radius, 4px);
                  min-height: 280px;
                  transition: none;
                }

                @media only screen and (hover: none) and (pointer: coarse) {
                  .type-picture-entity {
                    min-height: 215px !important;
                  }
                }

          # Actions - Alarm is on
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "armed_home"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.alarm_disarm_silently
                  name: "Let Dog Out"
                  icon: mdi:dog-side
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.alarm_disarm_silently

                - type: entity-button
                  entity: script.good_morning
                  name: "Good Morning"
                  icon: mdi:brightness-5
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.turn_on
                    service_data:
                      entity_id: script.good_morning

          # Actions - Alarm is off temporarily
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: script.alarm_disarm_silently
                state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.alarm_disarm_silently
                  name: "Alarm Will Automatically Arm"
                  icon: mdi:timer
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    confirmation:
                      text: "Are you sure you want to leave the alarm off?"
                    service: script.turn_off
                    service_data:
                      entity_id: script.alarm_disarm_silently

          # Actions - Alarm is off
          - type: conditional
            conditions:
              - entity: alarm_control_panel.abode_alarm
                state: "disarmed"
              - entity: script.alarm_disarm_silently
                state_not: "on"
            card:
              type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: scene.dinner_lights
                      name: "Dinner"
                      icon: mdi:food-fork-drink
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.dinner_lights
                    - type: entity-button
                      entity: scene.mood_lights
                      name: "Movie"
                      icon: mdi:movie
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.mood_lights

                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: scene.good_night
                      name: "Good Night"
                      icon: mdi:brightness-2
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.good_night
                    - type: entity-button
                      entity: scene.away
                      name: "Away"
                      icon: mdi:exit-run
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: scene.turn_on
                        service_data:
                          entity_id: scene.away


          - type: vertical-stack
            title: "Status"
            cards:
              - type: markdown
                entity_id:
                  - sensor.outdoor_forecast
                  - sensor.outside_temp
                  - sensor.outdoor_forecast
                  - sensor.outside_rain_daily
                  - alarm_control_panel.abode_alarm
                content: >
                  <ha-icon icon="{{ state_attr('sensor.outdoor_forecast', 'icon') }}"></ha-icon> Outside {{ states('sensor.outside_temp')|round(0, default=0) }}°F {{ states('sensor.outdoor_forecast') }}

                  {% if states('sensor.outside_rain_daily')|float(0) %}
                    <ha-icon icon="mdi:weather-rainy"></ha-icon> It rained {{ states('sensor.outside_rain_daily') }}" today

                  {% endif %}
                  {% if states('sensor.air_pollution_level') != 'good' %}
                    <ha-icon icon="mdi:weather-fog"></ha-icon> Air quality is {{ states('sensor.air_pollution_level') }}

                  {% endif %}
                  {% if is_state('alarm_control_panel.abode_alarm', 'armed_home') %}
                    <ha-icon icon="mdi:shield-home-outline"></ha-icon> Alarm is armed home
                  {% elif is_state('alarm_control_panel.abode_alarm', 'armed_away') %}
                    <ha-icon icon="mdi:shield-lock-outline"></ha-icon> Alarm is armed away
                  {% endif %}

              - type: 'custom:auto-entities'
                card:
                  type: entities
                  show_header_toggle: false
                filter:
                  include:
                    - group: group.doors_and_windows
                    - group: group.entrances
                  exclude:
                    - state: "off"
                    - state: "unavailable"
                show_empty: false

  - title: "Inside"
    cards:
      - type: entities
        title: "Lights"
        state_color: true
        show_header_toggle: true
        entities:
          # Family Room Area
          - type: custom:multiple-entity-row
            entity: light.family_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.family_room_status
                name: false
          - entity: light.kitchen
          - entity: switch.kitchen_cabinets
            name: "Cabinets"
            icon: mdi:lightbulb
          - entity: light.island

          - type: divider

          # Living Room Area
          - type: custom:multiple-entity-row
            entity: switch.living_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.living_room_status
                name: false
          - entity: light.dining_room
          - entity: light.entryway
          - entity: switch.hallway
            icon: mdi:lightbulb

          - type: divider

          # Bedrooms
          - type: custom:multiple-entity-row
            entity: light.master_bedroom
            toggle: true
            entities:
              - entity: sensor.master_bedroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: switch.boys_bedroom
            toggle: true
            entities:
              - entity: sensor.boys_bedroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: light.play_room
            toggle: true
            entities:
              - entity: sensor.playroom_status
                name: false
          - type: custom:multiple-entity-row
            entity: light.guest_bedroom
            toggle: true
            entities:
              - entity: sensor.guest_bedroom_status
                name: false

      - type: entities
        title: "Media"
        state_color: true
        show_header_toggle: false
        entities:
          - entity: switch.family_room_apple_tv
            icon: mdi:television
          - entity: switch.family_room_speakers
            icon: mdi:speaker

      - type: entities
        title: "Climate"
        state_color: true
        show_header_toggle: false
        entities:
          - type: custom:multiple-entity-row
            entity: climate.home
            name: "Climate"
            show_state: false
            state_color: false
            entities:
              - attribute: current_temperature
                name: "Temperature"
                unit: "°F"
              - attribute: preset_mode
                name: "Mode"
          - entity: switch.house_fan_switch
            icon: mdi:fan
            name: "Fan"
          - type: section
          - entity: automation.climate_windows_open
            state_color: false
            name: Turn off when windows open

  - title: "Outside"
    cards:
      - type: glance
        title: "Weather"
        show_name: false
        entities:
          - entity: sensor.outside_temp
          - entity: sensor.outside_humidity
            icon: mdi:water-percent
          - entity: sensor.outside_wind_speed
            icon: mdi:weather-windy
          - entity: sensor.outside_uv
            icon: mdi:weather-sunny
      - type: entities
        title: "Landscape"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: switch.front_yard_switch
            icon: mdi:lightbulb
          - entity: switch.back_yard_switch
            icon: mdi:lightbulb
          - entity: switch.front_landscape
            icon: mdi:flower-tulip
          - entity: switch.back_landscape
            icon: mdi:flower-tulip
          - entity: switch.pool_light
            icon: mdi:pool
          - entity: switch.fountain
            icon: mdi:cup-water
          - type: section
          - entity: automation.landscape_back_door_light
            name: "Automate Back Lights"
          - entity: automation.landscape_fountain
            name: "Automate Fountain"