kiosk_mode:
  hide_header: false
  hide_sidebar: false
  hide_menubutton: false
  hide_overflow: true

views:
  - title: "Home"
    path: "home"
    cards:
      - type: vertical-stack
        cards:
          # Header and alarm
          - type: entity
            name: "Home"
            entity: alarm_control_panel.alarm
            card_mod:
              style: |
                :host ha-card {
                  background: none;
                  border: 0;
                }

                :host ha-card .header {
                  padding: 0 0 0 5px;
                }

                :host ha-card .name {
                  color: var(--primary-text-color);
                  font-size: 24px;
                  font-weight: 400;
                }

                :host ha-card .info {
                  position: absolute;
                  top: 10px;
                  right: 10px;
                }

                :host ha-card .value {
                  font-size: 16px;
                  font-weight: 500;
                }

          # Status  
          - type: markdown
            entity_id:
              - sensor.outdoor_forecast
              - sensor.outside_temp
              - sensor.outside_rain_daily
              - sensor.outside_uv
              - sensor.air_pollution_level
              - counter.camera_motion
            content: |
              {%- if states('sensor.outside_temp') -%}
                <ha-icon icon="mdi:weather-rainy"></ha-icon> Currently {{ states('sensor.outside_temp')|round(0, default=0) }}°F&nbsp; 

                {%- if states('sensor.outside_rain_daily')|float(0) -%}
                  with {{ states('sensor.outside_rain_daily') }}" of rain
                {%- else -%}
                  {{ states('sensor.outdoor_forecast') }}
                {%- endif -%}
              {%- endif -%}
              {% if states('sensor.air_pollution_level') != 'good' %}
                <ha-icon icon="mdi:weather-fog"></ha-icon> Air quality is {{ states('sensor.air_pollution_level') }}
              {%- endif -%}
              {% if states('counter.camera_motion')|float(0) > 0 %}
                <ha-icon icon="mdi:alert-outline"></ha-icon> {{ states('counter.camera_motion') }} events today
              {%- endif -%}
              {% if is_state('input_boolean.guest_mode', 'on') %}
                <ha-icon icon="mdi:bed"></ha-icon> Guest mode is enabled
              {%- endif -%}
            card_mod:
              style: |
                :host ha-card { 
                  background: none;
                  border: 0;
                  margin: 0 0 5px -10px;
                  color: var(--secondary-text-color);
                  line-height: 2.25em;
                }

          # House Pic
          - type: picture-entity
            entity: camera.front_patio
            show_name: false
            show_state: false
            tap_action: 
              action: 'navigate'
              navigation_path: '/lovelace/cameras'
            card_mod:
              style: |
                :host ha-card { 
                  margin: 0 -8px 20px;
                  border: 0;
                  border-radius: 0;
                }
                

          # Actions - Alarm is on
          - type: conditional
            conditions:
              - entity: alarm_control_panel.alarm
                state: "armed_home"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.let_dog_out
                  name: "Let Dog Out"
                  icon: mdi:dog-side
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.let_dog_out

                - type: entity-button
                  entity: script.good_morning
                  name: "Good Morning"
                  icon: mdi:brightness-5
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    service: script.good_morning

          # Actions - Alarm is off temporarily
          - type: conditional
            conditions:
              - entity: alarm_control_panel.alarm
                state: "disarmed"
              - entity: script.let_dog_out
                state: "on"
            card:
              type: horizontal-stack
              cards:
                - type: entity-button
                  entity: script.let_dog_out
                  name: "Alarm Will Automatically Arm"
                  icon: mdi:timer
                  icon_height: 1.5em
                  tap_action:
                    action: call-service
                    confirmation:
                      text: "Are you sure you want to leave the alarm off?"
                    service: script.turn_off
                    service_data:
                      entity_id: script.let_dog_out

          # Actions - Alarm is off
          - type: conditional
            conditions:
              - entity: alarm_control_panel.alarm
                state: "disarmed"
              - entity: script.let_dog_out
                state_not: "on"
            card:
              type: vertical-stack
              cards:
                - type: horizontal-stack
                  cards:
                    - type: entity-button
                      entity: script.dinner_lights
                      name: "Dinner"
                      icon: mdi:pot-steam
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.dinner_lights
                    - type: entity-button
                      entity: script.mood_lights
                      name: "Mood"
                      icon: mdi:movie-filter
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.mood_lights

                - type: horizontal-stack
                  cards:
                    - type: conditional
                      conditions:
                        - entity: sun.sun
                          state: "above_horizon"
                      card:
                        type: entity-button
                        entity: script.good_morning
                        name: "Good Morning"
                        icon: mdi:brightness-5
                        icon_height: 1.5em
                        tap_action:
                          action: call-service
                          service: script.good_morning
                    - type: conditional
                      conditions:
                        - entity: sun.sun
                          state_not: "above_horizon"
                      card:
                        type: entity-button
                        entity: script.good_night
                        name: "Good Night"
                        icon: mdi:brightness-2
                        icon_height: 1.5em
                        tap_action:
                          action: call-service
                          service: script.good_night
                    - type: entity-button
                      entity: script.away
                      name: "Away"
                      icon: mdi:exit-run
                      icon_height: 1.5em
                      tap_action:
                        action: call-service
                        service: script.away


          - type: vertical-stack
            title: " "
            cards:
              - type: 'custom:auto-entities'
                card:
                  type: entities
                  show_header_toggle: false
                filter:
                  include:
                    - group: binary_sensor.garage_doors
                    - group: binary_sensor.doors_and_windows
                  exclude:
                    - state: "off"
                    - state: "unavailable"
                show_empty: false

  - title: "Inside"
    path: "inside"
    cards:
      - type: entities
        title: "Lights"
        state_color: true
        show_header_toggle: true
        entities:
          - type: divider

          # Family Room Area
          - type: custom:multiple-entity-row
            entity: light.family_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.family_room_temperature
                name: false
                format: 'precision0'
          - entity: light.kitchen
          - entity: light.kitchen_cabinets
          - entity: light.island

          - type: divider

          # Living Room Area
          - type: custom:multiple-entity-row
            entity: light.living_room
            icon: mdi:lightbulb
            toggle: true
            entities:
              - entity: sensor.living_room_temperature
                name: false
                format: 'precision0'
          - entity: light.dining_room
          - entity: light.entryway
          - entity: light.hallway

          - type: divider

          # Bedrooms
          - type: custom:multiple-entity-row
            entity: light.master_bedroom
            toggle: true
            entities:
              - entity: sensor.master_bedroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: light.boys_bedroom
            toggle: true
            entities:
              - entity: sensor.boys_bedroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: light.play_room
            toggle: true
            entities:
              - entity: sensor.playroom_temperature
                name: false
                format: 'precision0'
          - type: custom:multiple-entity-row
            entity: light.guest_bedroom
            toggle: true
            entities:
              - entity: sensor.guest_bedroom_temperature
                name: false
                format: 'precision0'

      - type: entities
        title: "Media"
        state_color: true
        show_header_toggle: false
        entities:
          - type: divider

          - entity: remote.family_room
          - type: custom:multiple-entity-row
            entity: media_player.family_room_speakers
            toggle: true
          - type: custom:multiple-entity-row
            entity: media_player.living_room_speakers
            toggle: true
          - type: custom:multiple-entity-row
            entity: media_player.playroom_speakers
            toggle: true
          - type: custom:multiple-entity-row
            entity: media_player.outside_speakers
            toggle: true

      - type: entities
        title: "Climate"
        state_color: true
        show_header_toggle: false
        entities:
          - type: divider

          - type: custom:multiple-entity-row
            entity: climate.home
            name: "Climate"
            show_state: false
            state_color: true
            entities:
              - attribute: current_temperature
                name: "Temperature"
                unit: "°F"
                format: 'precision0'
          - entity: switch.house_fan
            icon: mdi:fan
            name: "Fan"
          - type: section
          - entity: automation.climate_windows_open
            state_color: false
            name: "Turn off when windows open"

  - title: "Outside"
    path: "outside"

    cards:
      - type: entities
        title: "Garages"
        state_color: false
        show_header_toggle: false
        entities:
          - type: divider

          - entity: cover.garage_door_3
          - entity: cover.garage_door_2
          - entity: cover.garage_door_1
      - type: entities
        title: "Landscape"
        state_color: false
        show_header_toggle: false
        entities:
          - type: divider

          - entity: light.front_door
          - entity: light.back_doors
          - entity: light.twinkle_lights
          - type: divider
          - entity: light.garage
            icon: mdi:garage
          - entity: switch.pool_light
            icon: mdi:pool
          - entity: switch.fountain
            icon: mdi:cup-water
          - type: divider
          - entity: switch.front_landscape
            icon: mdi:flower-tulip
          - entity: switch.back_landscape
            icon: mdi:flower-tulip
      - type: entities
        title: "Settings"
        state_color: false
        show_header_toggle: false
        entities:
          - entity: automation.cameras_doorbell
            name: "Doorbell press alerts"
          - entity: automation.cameras_doorbell_motion
            name: "Doorbell motion alerts"
          - entity: automation.landscape_back_door_light
            name: "Turn back lights on with doors"
          - entity: automation.landscape_fountain
            name: "Turn fountain on automatically"

  - title: "Cameras"
    path: "cameras"
    visible: false
    cards:
      - type: grid
        square: false
        columns: 2
        title: "Latest Events"
        cards:
          - type: 'custom:config-template-card'
            entities:
              - camera.latest_doorbell
            card:
              type: picture-entity
              name: "Doorbell"
              aspect_ratio: 16x9
              entity: camera.latest_doorbell
              show_state: false
              tap_action:
                action: url
                url_path: "${ states['camera.latest_doorbell'].attributes.entity_picture }"
              hold_action:
                action: none

          - type: 'custom:config-template-card'
            entities:
              - camera.latest_mailbox
            card:
              type: picture-entity
              name: "Mailbox"
              aspect_ratio: 16x9
              entity: camera.latest_mailbox
              show_state: false
              tap_action:
                action: url
                url_path: "${ states['camera.latest_mailbox'].attributes.entity_picture }"
              hold_action:
                action: none
      - type: grid
        square: false
        columns: 1
        title: "Live Cameras"
        cards:
          - type: picture-glance
            camera_image: camera.front_patio
            entities:
              - entity: light.front_door
          - type: picture-glance
            camera_image: camera.driveway
            entities:
              - entity: light.front_door
          - type: picture-glance
            camera_image: camera.family_room
            entities:
              - entity: light.kitchen_area
                icon: mdi:lightbulb
          - type: picture-glance
            camera_image: camera.living_room
            entities:
              - entity: light.living_area
                icon: mdi:lightbulb
          - type: picture-glance
            camera_image: camera.back_yard
            entities: []
          - type: picture-glance
            camera_image: camera.front_door
            aspect_ratio: 16x9
            entities:
              - entity: light.front_door