title: Home

views:
  - title: "Inside"
    cards:
      - type: conditional
        conditions:
          - entity: alarm_control_panel.alarm
            state: "armed_home"
        card:
          type: entities
          entities:
            - entity: scene.let_dog_out
              icon: mdi:dog-side

      - type: entities
        title: "Lights"
        show_header_toggle: true
        entities:
          - entity: light.family_room_lights_level
          - entity: light.island_lights_level
          - entity: light.kitchen
          - entity: switch.kitchen_cabinets_switch
            icon: mdi:lightbulb
          - entity: light.pantry_light_level
          - entity: light.dining_room_lights_level
          - entity: switch.living_room_switch
            icon: mdi:lightbulb
          - entity: switch.entryway_light_switch
            icon: mdi:lightbulb
          - entity: switch.hallway_light_switch
            icon: mdi:lightbulb
          - entity: switch.guest_room_switch
            icon: mdi:lightbulb
          - entity: light.masons_room_level
          - entity: light.master_bedroom_level

      - type: entities
        title: "Media"
        show_header_toggle: false
        entities:
          - entity: sensor.family_room_media
            name: "Family Room"
            icon: mdi:television
          - entity: input_select.family_room_media
            icon: mdi:remote

      - type: conditional
        conditions:
          - entity: sensor.family_room_media
            state: "Speakers"
        card:
          type: entities
          entities:
            - entity: script.back_yard_speakers
              name: "Play Outside"
              icon: mdi:speaker

      - type: entities
        title: "Climate"
        show_header_toggle: false
        entities:
          - entity: sensor.climate_mode
            name: "Mode"
          - entity: switch.house_fan_switch
            icon: mdi:fan
          - sensor.family_room_status
          - sensor.living_room_status
          - sensor.masons_room_status
          - sensor.brinks_room_status
          - sensor.master_bedroom_status
          - sensor.guest_bedroom_status

      - type: entities
        title: "Scenes"
        show_header_toggle: false
        entities:
          - entity: scene.good_morning
            icon: mdi:brightness-5
          - entity: scene.movie_time
            icon: mdi:movie
          - entity: scene.dinner_time
            icon: mdi:food-variant
          - entity: scene.good_night
            icon: mdi:brightness-2
          - entity: scene.i_m_leaving
            icon: mdi:exit-run

  - title: "Outside"
    cards:
      - type: entities
        title: "Weather"
        show_header_toggle: false
        entities:
          - entity: sensor.outdoor_forecast
            name: "Forecast"
          - entity: sensor.outside_temp
            name: "Temperature"
          - entity: sensor.outside_humidity
            name: "Humidity"
            icon: mdi:water-percent
          - entity: sensor.outside_rain_daily
            name: "Rain"
            icon: mdi:water


      - type: entities
        title: "Landscape"
        show_header_toggle: false
        entities:
          - entity: switch.front_yard_switch
            icon: mdi:lightbulb
          - entity: switch.back_yard_switch
            icon: mdi:lightbulb
          - entity: switch.front_landscape
            icon: mdi:lightbulb
          - entity: switch.back_landscape
            icon: mdi:lightbulb
          - entity: switch.fountain
            icon: mdi:cup-water

      - type: entity-filter
        card:
          type: entities
          title: "Security"
          show_header_toggle: false
        state_filter:
          - "on"
          - "disarmed"
          - "armed_home"
          - "armed_away"
        show_empty: false
        entities:
          - entity: alarm_control_panel.alarm
          - entity: binary_sensor.front_door
            icon: mdi:door
          - entity: binary_sensor.family_room_doors
            icon: mdi:door
          - entity: binary_sensor.dining_room_window
            icon: mdi:window-closed
          - entity: binary_sensor.living_room_window_left
            icon: mdi:window-closed
          - entity: binary_sensor.living_room_window_right
            icon: mdi:window-closed
          - entity: binary_sensor.kitchen_window
            icon: mdi:window-closed
          - entity: binary_sensor.masons_window
            icon: mdi:window-closed
          - entity: binary_sensor.brinks_window
            icon: mdi:window-closed
          - entity: binary_sensor.guest_window
            icon: mdi:window-closed
          - entity: binary_sensor.master_bedroom_window
            icon: mdi:window-closed
          - entity: binary_sensor.master_bedroom_doors
            icon: mdi:door
          - entity: binary_sensor.laundry_room_door
            icon: mdi:door
          - entity: binary_sensor.jeffs_garage_door_sensor
            icon: mdi:garage
          - entity: binary_sensor.jillians_garage_door_sensor
            icon: mdi:garage
          - entity: binary_sensor.guest_garage_door_sensor
            icon: mdi:garage

  - title: "Status"
    cards:

      - type: entities
        title: "Settings"
        show_header_toggle: false
        entities:
          - entity: input_select.delay_timer
            name: "Lights Off Timer"
            icon: mdi:lightbulb
          - entity: switch.skybell_front_door_do_not_disturb
            name: "Mute Doorbell"
          - entity: automation.doorbell_notifications
            name: "Doorbell Pictures"
          - entity: automation.alarm_say_status
            name: "Speak Alarm Status"
          - entity: automation.garage_door_open
            name: "Garage Notifications"
          - entity: automation.landscape_fountain
            name: "Automate Fountain"

      - type: entities
        title: "Energy"
        show_header_toggle: false
        entities:
          - entity: sensor.home_energy_meter_power
            icon: mdi:power-socket-us
          - entity: sensor.home_energy_meter_energy_3
            icon: mdi:battery-charging
          - entity: sensor.home_energy_meter_current
            icon: mdi:current-ac
          - entity: sensor.home_energy_meter_voltage
            icon: mdi:flash

      - type: entities
        title: "Network"
        show_header_toggle: false
        entities:
          - entity: binary_sensor.internet
            name: "Internet"
            icon: mdi:access-point-network
