kiosk_mode:
  hide_header: false
  hide_sidebar: false
  hide_menubutton: false
  hide_overflow: true
  admin_settings:
    hide_overflow: false

views:
  - !include views/home.yaml
  - !include views/inside.yaml
  - !include views/outside.yaml
  - !include views/cameras.yaml
  - !include views/settings.yaml
