kiosk_mode:
  hide_header: false
  hide_sidebar: false
  hide_menubutton: false
  hide_overflow: true
  admin_settings:
    hide_overflow: false

views:
  - !include views/v1/home.yaml
  - !include views/v1/inside.yaml
  - !include views/v1/outside.yaml
  - !include views/v1/cameras.yaml
  - !include views/v1/energy.yaml
  - !include views/v1/climate.yaml
  - !include views/v1/settings.yaml
