title: "Settings"
path: "settings"
visible: false
cards:
  
  - type: vertical-stack
    cards:
      # Settings
      - type: markdown
        content: "Settings (reset daily)"
        theme: nocard
        card_mod:
          style: |
            :host ha-card {
              margin: 20px 0 0 0;
              transition: none;
            }

      - type: entities
        state_color: false
        entities:
          - entity: input_boolean.camera_motion_enabled
            name: "Camera Motion Alerts"

          - entity: automation.cameras_doorbell
            name: "Doorbell Alerts"

          - entity: automation.cameras_mailbox_open
            name: "Mailbox Alerts"

          - entity: automation.climate_windows_open
            name: "Turn HVAC Off When Windows Open"

          - entity: automation.landscape_back_door_light
            name: "Turn Back Lights on Automatically"
          - entity: automation.landscape_fountain
            name: "Turn Fountain On Automatically"

      # Batteries
      - type: markdown
        content: "Battery Levels"
        theme: nocard
        card_mod:
          style: |
            :host ha-card {
              margin: 20px 0 0 0;
              transition: none;
            }

      - type: entities
        state_color: false
        entities:
          - entity: sensor.ups_battery_charge
            name: "UPS"
          - entity: sensor.mailbox_battery_level
            name: "Mailbox Sensor"
          - entity: sensor.garage_side_door_battery_level
            name: "Garage Side Door"
          - entity: sensor.garage_temp_battery
            name: "Garage Temperature"
          - entity: sensor.outside_battery
            name: "Weather Station"