title: "Settings"
path: "settings"
visible: false
cards:
  
  # Disclaimer
  - type: markdown
    content: |
      Settings reset daily
    theme: nocard
    card_mod:
      style: |
        :host ha-card {
          margin: 20px 0 0 0;
          transition: none;
        }

  # Automations
  - type: entities
    state_color: true
    entities:
      - entity: automation.cameras_doorbell
        name: "Doorbell press alerts"
      - entity: automation.cameras_doorbell_motion
        name: "Doorbell motion alerts"
      - entity: automation.cameras_mailbox_open
        name: "Mailbox motion alerts"
      - entity: automation.landscape_back_door_light
        name: "Turn back lights on with doors"
      - entity: automation.landscape_fountain
        name: "Turn fountain on automatically"