title: "Settings"
path: "settings"
visible: false
cards:
  
  - type: vertical-stack
    cards:
      # Settings
      - type: markdown
        content: "Settings (reset daily)"
        theme: nocard
        card_mod:
          style: |
            :host ha-card {
              margin: 20px 0 0 0;
              transition: none;
            }

      - type: entities
        state_color: false
        entities:
          - entity: automation.cameras_doorbell
            name: "Doorbell Alerts"

          - entity: automation.cameras_mailbox_open
            name: "Mailbox Alerts"

          - entity: automation.climate_windows_open
            name: "Turn HVAC Off When Windows Open"

          - entity: automation.landscape_back_door_light
            name: "Turn Back Lights on Automatically"
          - entity: automation.landscape_fountain
            name: "Turn Fountain On Automatically"

      # Batteries
      - type: markdown
        content: "Battery Levels"
        theme: nocard
        card_mod:
          style: |
            :host ha-card {
              margin: 20px 0 0 0;
              transition: none;
            }

      - type: entities
        state_color: false
        entities:
          - entity: sensor.ups_battery_charge
            name: "UPS"

          # disabling as these don't report correctly with homekit
          # - type: section
          # - entity: sensor.family_room_battery
          #   name: "Family Room Temperature Sensor"
          # - entity: sensor.living_room_battery
          #   name: "Living Room Temperature Sensor"
          # - entity: sensor.boys_bedroom_battery
          #   name: "Boys Bedroom Temperature Sensor"
          # - entity: sensor.guest_bedroom_battery
          #   name: "Office Temperature Sensor"
          # - entity: sensor.master_bedroom_battery
          #   name: "Master Bedroom Temperature Sensor"
          # - entity: sensor.playroom_battery
          #   name: "Playroom Bedroom Temperature Sensor"
          # - entity: sensor.master_bedroom_battery
          #   name: "Master Bedroom Temperature Sensor"

          - entity: sensor.mailbox_battery_level
            name: "Mailbox"
          - entity: sensor.outside_battery
            name: "Weather Station"