extra_module_url:
  - /local/community/lovelace-card-mod/card-mod.js
  - /local/community/Bubble-Card/bubble-card.js 


# Colors - https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color.globals.ts
themes:
  nocard:
    card-mod-theme: nocard 

    ha-card-border-width: "0"
    ha-card-border-radius: "0"
    card-background-color: "transparent"

  subview:
    card-mod-theme: subview 

    primary-background-color: "#313131" 
    card-background-color: "#3D3D3D"

    bubble-button-main-background-color: "var(--card-background-color)"
    bubble-button-icon-background-color: "var(--primary-background-color)"
    bubble-main-background-color: "var(--card-background-color)"

  apptheme:
    card-mod-theme: apptheme
     
    primary-background-color: "#3D3D3D"
    card-background-color: "#313131"
    secondary-background-color: "var(--primary-background-color)"

    primary-text-color: "#E0E0E0"
    secondary-text-color: "#E0E0E0"

    accent-color: "#F3BB00"

    # Header
    app-header-text-color: "var(--primary-text-color)"
    app-header-background-color: "var(--primary-background-color)"
    app-header-selection-bar-color: "transparent"
    mdc-top-app-bar-fixed-box-shadow: "none"

    # Cards
    ha-card-border-width: "1px"
    ha-card-border-radius: "12px"
    ha-card-header-font-size: "15px"

    bubble-border-radius: "28px"
    bubble-light-color: "var(--accent-color)"

    bubble-main-background-color: "var(--card-background-color)"
    bubble-icon-background-color: "var(--primary-background-color)"
    bubble-pop-up-main-background-color: "var(--card-background-color)"
    bubble-button-main-background-color: "var(--card-background-color)"
    bubble-button-icon-background-color: "var(--primary-background-color)"

    divider-color: "rgba(0, 0, 0, 0.15)"
    code-editor-background-color: "#000"

    # Icons
    state-icon-color: "#E0E0E0"
    state-active-color: "var(--accent-color)"
    state-inactive-color: "var(--state-icon-color)"

    state-light-active-color: "var(--accent-color)"
    state-binary_sensor-active-color: "var(--accent-color)"
    state-cover-open-color: "var(--accent-color)"
    state-media_player-active-color: "var(--accent-color)"
    state-climate-auto-color: "var(--accent-color)"
    state-climate-cool-color: "var(--accent-color)"
    state-climate-heat-color: "var(--accent-color)"
    state-climate-fan_only-color: "var(--accent-color)"


    # CSS Overrides
    card-mod-root: |
      .header {
        position: relative !important;
        top: auto !important;
        height: auto !important;
        width: auto !important;
      }

      .header .main-title {
        font-size: 1.3em;
        font-weight: bold;
      }

      @media only screen and (hover: none) and (pointer: coarse) {
        .header .main-title {
          margin-left: 10px;
        }
      }
