extra_module_url:
  - /local/community/lovelace-card-mod/card-mod.js
  - /local/community/Bubble-Card/bubble-card.js 

themes:
  nocard:
    ha-card-border-width: "0"
    ha-card-border-radius: "0"
    card-background-color: "transparent"

  subview:
    primary-background-color: "#313131" 
    card-background-color: "#3D3D3D"

    bubble-button-main-background-color: "var(--card-background-color)"
    bubble-button-icon-background-color: "var(--card-background-color)"
    bubble-main-background-color: "var(--card-background-color)"


  apptheme:
    # Colors - https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color.globals.ts
    
    primary-background-color: "#3D3D3D"
    card-background-color: "#313131"
    secondary-background-color: "var(--primary-background-color)"

    primary-text-color: "#E0E0E0"
    secondary-text-color: "#E0E0E0"

    accent-color: "#F3BB00"

    # Header
    app-header-text-color: "var(--primary-text-color)"
    app-header-background-color: "var(--primary-background-color)"
    app-header-selection-bar-color: "transparent"
    mdc-top-app-bar-fixed-box-shadow: "none"

    # Cards
    ha-card-border-width: "1px"
    ha-card-border-radius: "12px"
    ha-card-header-font-size: "16px"

    bubble-border-radius: "28px"
    #bubble-accent-color: "var(--accent-color)"
    bubble-light-color: "var(--accent-color)"

    bubble-main-background-color: "var(--card-background-color)"
    bubble-icon-background-color: "var(--primary-background-color)"
    bubble-pop-up-main-background-color: "var(--card-background-color)"
    bubble-button-main-background-color: "var(--card-background-color)"
    bubble-button-icon-background-color: "var(--card-background-color)"

    divider-color: "rgba(0, 0, 0, 0.15)"
    code-editor-background-color: "#000"

    # Icons
    state-icon-color: "#E0E0E0"
    state-active-color: "var(--accent-color)"
    state-inactive-color: "var(--state-icon-color)"

    state-light-active-color: "var(--state-active-color)"
    state-binary_sensor-active-color: "var(--state-active-color)"
    state-cover-active-color: "var(--state-active-color)"
    state-media_player-active-color: "var(--state-active-color)"
    state-cover-active-color: "var(--state-active-color)"
    state-climate-auto-color: "var(--state-active-color)"
    state-climate-cool-color: "var(--state-active-color)"
    state-climate-heat-color: "var(--state-active-color)"
    state-climate-fan_only-color: "var(--state-active-color)"

    # CSS Overrides
    card-mod-theme: apptheme
    card-mod-root: |
      .header {
        position: relative !important;
        top: auto !important;
        height: auto !important;
        width: auto !important;
      }

      .header .main-title {
        font-size: 1.3em;
        font-weight: bold;
      }

      @media only screen and (hover: none) and (pointer: coarse) {
        .header .main-title {
          margin-left: 10px;
        }
      }

  home:
    # Colors
    # https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts
    primary-background-color: "#F7F8F9"
    secondary-background-color: "#F4F5F6"
    card-background-color: "#FFF"

    primary-text-color: "#555"
    secondary-text-color: "#999"
    disabled-text-color: "#B3B3B3"

    app-header-text-color: "#fff"
    app-header-background-color: "#555"
    app-header-selection-bar-color: "transparent"
    
    divider-color: "rgba(0, 0, 0, 0.15)"
    state-icon-color: "#999"

    switch-checked-button-color: "#FFF"
    switch-unchecked-button-color: "#FFF"
    switch-checked-track-color: "#0077FF"
    switch-unchecked-track-color: "#999"

    state-cover-open-color: "var(--state-active-color)"
    state-media_player-speaker-playing-color: "var(--state-active-color)"

    # General settings
    ha-card-border-width: "1px"
    ha-card-border-radius: "4px"
    
    ha-picture-icon-button-on-color: "var(--state-active-color)"
    ha-picture-card-background-color: "rgba(0, 0, 0, 0.4)"

    # Pin header on bottom of screen for mobile
    card-mod-theme: home
    card-mod-root: |
      @media only screen and (hover: none) and (pointer: coarse) {
        #view {
          margin-top: -50px !important;
          padding-bottom: 80px !important;
        }

        .header {
          position: fixed;
          top: auto !important;
          bottom: 0;
          height: 80px;
        }
      }