extra_module_url:
  - /hacsfiles/lovelace-card-mod/card-mod.js

themes:
  nocard:
    ha-card-border-width: "0"
    ha-card-border-radius: "0"
    card-background-color: "transparent"

  home:
    # Colors
    # https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts
    primary-background-color: "#F7F8F9"
    secondary-background-color: "#F4F5F6"
    card-background-color: "#FFF"

    primary-text-color: "#555"
    secondary-text-color: "#999"
    disabled-text-color: "#B3B3B3"

    app-header-text-color: "#fff"
    app-header-background-color: "#555"
    app-header-selection-bar-color: "transparent"
    
    divider-color: "rgba(0, 0, 0, 0.15)"
    state-icon-color: "#999"

    switch-checked-button-color: "#FFF"
    switch-unchecked-button-color: "#FFF"
    switch-checked-track-color: "#0077FF"
    switch-unchecked-track-color: "#999"

    state-cover-open-color: "var(--state-active-color)"
    state-media_player-speaker-playing-color: "var(--state-active-color)"

    # General settings
    ha-card-border-width: "1px"
    ha-card-border-radius: "4px"
    
    ha-picture-icon-button-on-color: "var(--state-active-color)"
    ha-picture-card-background-color: "rgba(0, 0, 0, 0.4)"

    # Pin header on bottom of screen for mobile
    card-mod-theme: home
    card-mod-root: |
      @media only screen and (hover: none) and (pointer: coarse) {
        #view {
          margin-top: -50px !important;
          padding-bottom: 80px !important;
        }

        .header {
          position: fixed;
          top: auto !important;
          bottom: 0;
          height: 80px;
        }
      }
