extra_module_url:
  - /local/community/lovelace-card-mod/card-mod.js

# Colors - https://github.com/home-assistant/frontend/blob/master/src/resources/theme/color.globals.ts
themes:
  no_card:
    card-mod-theme: no_card

    primary-text-color: "#fff"
    secondary-text-color: "#ccc"

    ha-card-border-width: "0"
    ha-card-border-radius: "0"
    card-background-color: "transparent"

    card-mod-card-yaml: |
      .: |
        .type-button ha-state-icon {
          filter: none !important;
        }

  padded_card:
    card-mod-theme: padded_card

    primary-text-color: "#fff"
    secondary-text-color: "#ccc"

    card-mod-card-yaml: |
      .: |
        ha-card {
          margin: 25px 0 0;
          height: auto;
          transition: none;
        }

        ha-card h1 {
          padding: 5px 15px 10px;
        }  

  round_button: 
    card-mod-theme: round_button

    primary-text-color: "#fff"
    secondary-text-color: "#ccc"

    ha-card-border-width: "1px"
    ha-card-border-radius: "28px"

    card-mod-card-yaml: |
      .: |
        .type-button {
          display: grid;
          grid-template-columns: 50px auto auto;
          justify-content: start;
          padding: 6px;
          transition: none !important;
        }

        .type-button ha-state-icon {
          padding: 10px;
          background: var(--primary-background-color);
          border-radius: 24px;
          filter: none !important;
        }

        .type-button ha-state-icon + span {
          margin-top: 0 !important;
        }

        .type-button .state:before {
          content:" • ";
          white-space: pre;
        }

  subview:
    card-mod-theme: subview 

    primary-text-color: "#fff"
    secondary-text-color: "#ccc"

    primary-background-color: "#313131" 
    card-background-color: "#3D3D3D"

  app_theme:
    card-mod-theme: app_theme
     
    primary-background-color: "#3D3D3D"
    card-background-color: "#313131"
    secondary-background-color: "var(--primary-background-color)"

    primary-text-color: "#E0E0E0"
    secondary-text-color: "#E0E0E0"

    accent-color: "#F3BB00"

    # Header
    app-header-text-color: "var(--primary-text-color)"
    app-header-background-color: "var(--primary-background-color)"
    app-header-selection-bar-color: "transparent"
    mdc-top-app-bar-fixed-box-shadow: "none"

    # Cards
    ha-card-border-width: "1px"
    ha-card-border-radius: "12px"
    ha-card-header-font-size: "15px"

    divider-color: "rgba(0, 0, 0, 0.15)"
    code-editor-background-color: "#000"

    # Icons
    state-icon-color: "#E0E0E0"
    state-active-color: "var(--accent-color)"
    state-inactive-color: "var(--state-icon-color)"

    state-light-active-color: "var(--accent-color)"
    state-binary_sensor-active-color: "var(--accent-color)"
    state-cover-open-color: "var(--accent-color)"
    state-media_player-on-color: "var(--accent-color)"
    state-media_player-active-color: "var(--accent-color)"
    state-climate-auto-color: "var(--accent-color)"
    state-climate-cool-color: "var(--accent-color)"
    state-climate-heat-color: "var(--accent-color)"
    state-climate-fan_only-color: "var(--accent-color)"

    # CSS Overrides
    card-mod-root: |
      .header {
        position: relative !important;
        top: auto !important;
        height: auto !important;
        width: auto !important;
      }

      .header .main-title {
        font-size: 1.3em;
        font-weight: bold;
      }

      @media only screen and (hover: none) and (pointer: coarse) {
        .header .main-title {
          margin-left: 10px;
        }
      }
