project_id: !secret google_assistant_id
service_account: !include ../google_assistant_key.json
report_state: true
expose_by_default: true
exposed_domains:
  - light
  - script
entity_config:
  light.bedroom_area:
    expose: false
  light.entrances:
    expose: false
  light.house:
    expose: false
  light.kitchen_1:
    expose: false
  light.kitchen_2:
    expose: false
  light.kitchen_area:
    expose: false
  light.living_area:
    expose: false
  script.dinner_lights:
    aliases:
      - DINNER_TIME
  script.good_morning:
    expose: false
  script.hvac_disable:
    expose: false
  script.hvac_resume:
    expose: false
  script.let_dog_out:
    expose: false
  script.mood_lights:
    aliases:
      - MOVIE_TIME
  switch.house_fan_switch:
    expose: true