project_id: !secret google_assistant_id
service_account: !include ../google_assistant_key.json
report_state: true
expose_by_default: false

entity_config:
  input_boolean.guest_mode_enabled:
    expose: true
  light.back_doors:
    expose: true
  light.boys_bedroom:
    expose: true
  light.dining_room:
    expose: true
  light.entryway:
    expose: true
  light.family_room:
    expose: true
  light.front_door:
    expose: true
  light.garage:
    expose: true
  light.guest_bedroom:
    expose: true
  light.hallway:
    expose: true
  light.island:
    expose: true
  light.kitchen:
    expose: true
  light.kitchen_cabinets:
    expose: true
  light.living_room:
    expose: true
  light.master_bedroom:
    expose: true
  light.twinkle_lights:
    expose: true
  light.play_room:
    expose: true
  script.away:
    expose: true
    name: "Away mode"
    room: house
  script.dinner_lights:
    expose: true
    name: "Dinner lights"
    room: house
    aliases:
      - DINNER_TIME
  script.good_night:
    expose: true
    name: "Good night"
    room: house
  script.mood_lights:
    expose: true
    name: "Mood lights"
    room: house
    aliases:
      - MOVIE_TIME
  switch.house_fan:
    expose: true