host: !secret influxdb_url
exclude:
  domains:
    - alert
    - automation
    - camera
    - configurator
    - group
    - persistent_notification
    - scene
    - script
    - zwave
    - alarm_control_panel
    - input_select