default: warning

logs:
  homeassistant.setup: error
  homeassistant.loader: error
  homeassistant.helpers.entity: error
  homeassistant.components.switch: error
  homeassistant.components.sensor: error
  homeassistant.components.scrape.sensor: error
  homeassistant.components.binary_sensor: error
  pychromecast.socket_client: critical
  custom_components.hacs: critical
  lomond: error
  skybellpy: error
  abodepy: error
  pyecobee: error
  slixmpp: error