mode: yaml

resources:
  - url: /local/community/custom-header/custom-header.js
    type: module
  - url: /local/community/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /local/community/lovelace-auto-entities/auto-entities.js
    type: module