dashboards:
  lovelace:
    mode: yaml
    filename: "ui-lovelace.yaml"
    title: "Overview"
    icon: "mdi:view-dashboard"
    show_in_sidebar: true

resource_mode: yaml

resources:
  - url: /hacsfiles/kiosk-mode/kiosk-mode.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /hacsfiles/hass-swipe-navigation/swipe-navigation.js
    type: module