mode: yaml

resources:
  - url:  /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module