mode: yaml

resources:
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /hacsfiles/kiosk-mode/kiosk-mode.js
    type: module

dashboards:
  lovelace-beta:
    mode: yaml
    filename: ui-beta.yaml
    title: "Home"
    show_in_sidebar: false

  lovelace-views:
    mode: yaml
    filename: ui-views.yaml
    title: "Views"
    show_in_sidebar: false