automation:
  - alias: Alarm - Status Away
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_away"
    action:
      - service: notify.phones
        data_template:
          message: >
            {%- if is_state("binary_sensor.doors_and_windows", "on") -%}
              Warning! The following are open: {{ expand("binary_sensor.doors_and_windows") | selectattr("state", "eq", "on") | map(attribute="name") | join(", ") }}
            {%- endif -%}
      - delay:
          minutes: 10
      - service: notify.phones
        data_template:
          message: >
            {%- if is_state("binary_sensor.garage_doors", "on") -%}
              The garage is still open: {{ expand("binary_sensor.garage_doors") | selectattr("state", "eq", "on") | map(attribute="name") | join(", ") }}
            {%- endif -%}

  - alias: Alarm - Status Home
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_home"
    action:
      - service: notify.master_bedroom
        data_template:
          message: >
            Alarm armed...

            {%- if is_state("input_boolean.guest_mode", "on") -%}
              Guest mode enabled...
            {%- endif -%}

            {%- if is_state("binary_sensor.doors_and_windows_and_garages", "on") -%}
              Warning! The following are open: {{ expand("binary_sensor.doors_and_windows_and_garages") | selectattr("state", "eq", "on") | map(attribute="name") | join(", ") }}
            {%- endif -%}

  - alias: Alarm - Status Disarmed
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "disarmed"
    action:
      - service: notify.master_bedroom
        data_template:
          message: "Alarm off"

  - alias: Alarm - Turn house off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "armed_away"
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.house_off

  - alias: Alarm - Alert
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "triggered"
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.house_alert
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Alarm alert!"
          data:
            entity_id: camera.front_door
            url: "/lovelace/cameras"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1