automation:
  - alias: Alarm - Status alerts
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_home"
        variables:
          target: "master_bedroom"
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "disarmed"
        variables:
          target: "master_bedroom"
      - platform: state
        entity_id: alarm_control_panel.alarm
        to: "armed_away"
        variables:
          target: "phones"

    condition:
      # Explicitly call out trigger states and this condition to protect against errors
      condition: template
      value_template: "{{ trigger.from_state.state != 'unavailable' }}"
    action:
      - service: notify.{{ target }}
        data_template:
          message: >
            {% set status = trigger.to_state.state %}

            {%- if status == "disarmed" -%}
              Alarm off
            {%- else -%}
              {%- if status == "armed_home" -%}
                Alarm armed...
              {%- endif -%}

              {%- if is_state("input_boolean.guest_mode", "on") -%}
                Guest mode enabled...
              {%- endif -%}

              {%- if is_state("binary_sensor.doors_and_windows_and_garages", "on") -%}
                Warning! The following are open: {{ expand("binary_sensor.doors_and_windows_and_garages") | selectattr("state", "eq", "on") | map(attribute="name") | join(", ") }}
              {%- endif -%}
            {%- endif -%}

  - alias: Alarm - Turn house off
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "armed_away"
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.house_off

  - alias: Alarm - Alert
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      to: "triggered"
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.house_alert
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Alarm alert!"
          data:
            entity_id: camera.front_door
            url: "/lovelace/cameras"
            push:
              sound:
                name: "default"
                critical: 1
                volume: 1
      - service: system_log.write
        data_template:
          message: "Alarm Event: {{ trigger.event.data }}"
          level: error
