camera:
  - platform: local_file
    name: Latest Doorbell 
    file_path: /config/www/cameras/doorbell.jpg
  - platform: local_file
    name: Latest Mailbox 
    file_path: /config/www/cameras/mailbox.jpg

amcrest:
  - name: Doorbell
    host: !secret amcrest_doorbell_ip
    username: !secret amcrest_doorbell_user
    password: !secret amcrest_doorbell_pass
    binary_sensors:
      - online
      - motion_detected

counter:
  camera_motion:
    name: "Camera Motion Counter"
    icon: mdi:alert
    initial: 0
    restore: True


automation:
  - alias: Cameras - Doorbell
    initial_state: True
    mode: single
    max_exceeded: silent
    trigger:
      platform: event
      event_type: amcrest
      event_data:
        event: "CallNoAnswered"
        payload:
          action: "Start"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.doorbell
          filename: "/config/www/cameras/doorbell.jpg"
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Doorbell"
          data:
            entity_id: camera.doorbell
            url: "/lovelace/cameras"
      - delay:
          minutes: 1

  - alias: Cameras - Doorbell motion
    initial_state: True
    mode: single
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell_motion_detected
      to: "on"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Front Door Motion"
          data:
            entity_id: camera.doorbell
            url: "/lovelace/cameras"

  - alias: Cameras - Doorbell motion person
    initial_state: True
    mode: single
    max_exceeded: silent
    trigger:
      platform: event
      event_type: amcrest
      event_data:
        event: "CrossRegionDetection"
        payload:
          action: "Start"
          data:
            Object:
              Action: "Appear"
              ObjectType: "Human"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.doorbell
          filename: "/config/www/cameras/doorbell.jpg"
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Front Door Motion (Person)"
          data:
            entity_id: camera.doorbell
            url: "/lovelace/cameras"

  - alias: Cameras - Doorbell offline
    initial_state: True
    trigger:
      platform: state
      entity_id: binary_sensor.doorbell_online
      to: "off"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Doorbell offline!"

  - alias: Cameras - Mailbox open
    initial_state: True
    mode: single
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.mailbox_motion
        to: "on"
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.driveway
          filename: "/config/www/cameras/mailbox.jpg"
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Mailbox motion detected!"
          data:
            url: "/lovelace/cameras"
            push:
              sound:
                name: "default"
                critical: "{{ (states('sun.sun') == 'below_horizon')|int }}"
                volume: "{{ (states('sun.sun') == 'below_horizon')|int }}"
      - delay:
          minutes: 1

  - alias: Cameras - Motion webhook
    initial_state: True
    trigger:
      - platform: webhook
        webhook_id: "camera_driveway_motion"
        local_only: True
      - platform: webhook
        webhook_id: "camera_front_door_motion"
        local_only: True
      - platform: webhook
        webhook_id: "camera_back_yard_motion"
        local_only: True
    action:
      - service: counter.increment
        target:
          entity_id: counter.camera_motion
          
  - alias: Cameras - Reset motion counter
    initial_state: True
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: counter.reset
        target:
          entity_id: counter.camera_motion
