group:
  Climate:
    entities:
      - sensor.climate_temp
      - sensor.climate_humidity
      - sensor.climate_mode
      - switch.house_fan_switch


homeassistant:
  customize:
    sensor.climate_temp:
      friendly_name: Temperature
    sensor.climate_humidity:
      friendly_name: Humidity
      icon: mdi:water
    sensor.climate_mode:
      friendly_name: Mode
      icon: mdi:thermostat
    sensor.meadowlands_temperature:
      hidden: true
    sensor.meadowlands_humidity:
      hidden: true
    switch.house_fan_switch:
      friendly_name: House Fan
      icon: mdi:fan


ecobee:
  api_key: !secret ecobee_api_key


sensor:
  - platform: template
    sensors:
      climate_temp:
        value_template: '{{states.climate.meadowlands.attributes.current_temperature}}'
        unit_of_measurement: °F

      climate_humidity:
        value_template: '{{states.climate.meadowlands.attributes.actual_humidity}}'
        unit_of_measurement: '%'

      climate_mode:
        value_template: '{% if states.climate.meadowlands.attributes.mode == "Away" %}Away{% else %}{{states.climate.meadowlands.attributes.operation_mode|capitalize}}{% endif %}'

      climate_operation:
        value_template: '{{states.climate.meadowlands.attributes.operation}}'


automation:
  - alias: Thermostat turns off AC when house fan turns on
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.house_fan_switch
      from: 'off'
      to: 'on'
    action:
      - condition: template
        value_template: '{{ states.climate.meadowlands.attributes.operation_mode == "cool" }}'
      - service: climate.set_temperature
        data:
          entity_id: climate.meadowlands
          temperature: 80

  - alias: Thermostat resumes when states revert
    initial_state: True
    hide_entity: True
    trigger:
      - platform: state
        entity_id: switch.house_fan_switch
        from: 'on'
        to: 'off'
      - platform: state
        entity_id: alarm_control_panel.simplisafe
        from: 'armed_away'
    action:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.meadowlands
