ecobee:
  api_key: !secret ecobee_api_key


sensor:
  - platform: template
    sensors:
      climate_mode:
        value_template: "{% if states.climate.home.attributes.preset_mode == 'away' %}Away{% else %}{{ states.climate.home.state|capitalize }}{% endif %}"

      climate_operation:
        value_template: "{{ states.climate.home.attributes.hvac_action != 'off' }}"

      family_room_status:
        friendly_name: Family Room
        value_template: "{{ states.sensor.family_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.family_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      living_room_status:
        friendly_name: Living Room
        value_template: "{{ states.sensor.living_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.living_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      masons_room_status:
        friendly_name: Mason's Bedroom
        value_template: "{{ states.sensor.masons_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.masons_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      brinks_room_status:
        friendly_name: Brink's Bedroom
        value_template: "{{ states.sensor.brinks_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.masons_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      master_bedroom_status:
        friendly_name: Master Bedroom
        value_template: "{{ states.sensor.master_bedroom_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      guest_bedroom_status:
        friendly_name: Guest Bedroom
        value_template: "{{ states.sensor.guest_bedroom_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

  - platform: awair
    access_token: !secret awair_access_token


automation:
  - alias: Climate - House fan disables HVAC
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.house_fan_switch
      from: "off"
      to: "on"
    action:
      # change the thermostat to a value higher/lower
      - service: climate.set_temperature
        data_template:
          entity_id: climate.home
          temperature: >
            {% if states.climate.home.state == 'cool' %}
              80
            {% else %}
              60
            {% endif %}

  - alias: Climate – Resume thermostat
    initial_state: True
    hide_entity: True
    trigger:
      - platform: state
        entity_id: switch.house_fan_switch
        from: "on"
        to: "off"
    action:
      - service: climate.ecobee_resume_program
        data:
          entity_id: climate.home
