sensor:
  - platform: template
    sensors:
      climate_operation:
        value_template: "{{ not is_state_attr('climate.home', 'hvac_action', 'idle') }}"


automation:
  - alias: Climate - Windows open
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.doors_and_windows
        to: "on"
        for: "00:20:00"
    condition:
      condition: template
      value_template: "{{ is_state('switch.house_fan', 'off') }}"
    action:
      - service: script.hvac_disable
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Turning HVAC off since {{ expand('binary_sensor.doors_and_windows') | selectattr('state', 'eq', 'on') | map(attribute='name')| join(', ') }} is open"
      - delay: "00:00:10"
      - wait_template: "{{ is_state('binary_sensor.doors_and_windows', 'off') }}"
      - service: script.hvac_resume

  - alias: Climate - Disable HVAC with house fan
    initial_state: True
    mode: single
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: switch.house_fan
      to: "on"
    action:
      - service: script.hvac_disable
      - delay: "00:01:00"
      - wait_template: "{{ is_state('binary_sensor.doors_and_windows', 'off') }}"
      - service: script.hvac_resume

  - alias: Climate - Notify cooler outside than inside
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.climate_operation
        to: "1"
    condition:
      condition: template
      value_template: "{{ is_state('alarm_control_panel.alarm', 'disarmed') and is_state('climate.home', 'cool') and state_attr('climate.home', 'temperature')|int > states('sensor.outside_temp')|int }}"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Open the windows – it's nicer outside than inside!"
      - delay:
          hours: 8