ecobee:
  api_key: !secret ecobee_api_key


sensor:
  - platform: awair
    access_token: !secret awair_access_token

  - platform: template
    sensors:
      climate_mode:
        value_template: >
          {%- if states.climate.home.attributes.preset_mode == 'away' -%}
            Away
          {%- else -%}
            {{ states.climate.home.state|capitalize }}
          {%- endif -%}

      climate_operation:
        value_template: >
          {% set operation = state_attr('climate.home', 'hvac_action') %}
          {%- if operation == 'cooling' or operation == "heating" -%}
            1
          {%- else -%}
            0
          {%- endif -%}

      family_room_status:
        friendly_name: Family Room
        value_template: "{{ states.sensor.family_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.family_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      living_room_status:
        friendly_name: Living Room
        value_template: "{{ states.sensor.living_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.living_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      masons_room_status:
        friendly_name: Mason's Bedroom
        value_template: "{{ states.sensor.masons_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.masons_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      brinks_room_status:
        friendly_name: Brink's Bedroom
        value_template: "{{ states.sensor.brinks_room_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.masons_room_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      master_bedroom_status:
        friendly_name: Master Bedroom
        value_template: "{{ states.sensor.master_bedroom_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}

      guest_bedroom_status:
        friendly_name: Guest Bedroom
        value_template: "{{ states.sensor.guest_bedroom_temperature.state|round|int }}"
        unit_of_measurement: °F
        entity_picture_template: >
          {%- if is_state("binary_sensor.master_bedroom_occupancy", "on") -%}
            /local/thermometer-on.svg
          {%- else -%}
            /local/thermometer.svg
          {%- endif -%}


automation:
  - alias: Climate - House Fan On/Off
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.house_fan_switch
    action:
      service_template: >
        {%- if trigger and trigger.to_state.state == "on" -%}
          script.house_fan_on
        {%- else -%}
          script.house_fan_off
        {%- endif -%}