sensor:
  - platform: template
    sensors:
      climate_operation:
        value_template: >
          {% set operation = state_attr('climate.home', 'hvac_action') %}
          {%- if operation == 'cooling' or operation == "heating" -%}1{%- else -%}0{%- endif -%}


automation:
  - alias: Climate - House Fan On
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.house_fan_switch
      to: "on"
      from: "off"
    action:
      - service: script.hvac_disable
      - delay: "00:00:10"
      - wait_template: "{{ is_state('group.doors_and_windows', 'off') }}"
      - service: script.hvac_resume

  - alias: Climate - House Fan with HVAC Running
    initial_state: True
    trigger:
      platform: state
      entity_id: sensor.climate_operation
      to: "1"
    condition:
      condition: template
      value_template: "{{ is_state('switch.house_fan_switch', 'on') }}"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "House fan is running with the HVAC on!"

  - alias: Climate - House Fan with Dryer Running
    initial_state: True
    trigger:
      - platform: state
        entity_id: 
          - switch.house_fan_switch
          - sensor.dryer
        from: "off"
        to: "on"
    condition:
      condition: template
      value_template: "{{ is_state('switch.house_fan_switch', 'on') and is_state('sensor.dryer', 'on') and is_state('binary_sensor.guest_window', 'on') }}"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "House fan is running with the dryer on!"

  - alias: Climate - Windows Open
    initial_state: True
    trigger:
      - platform: state
        entity_id: group.doors_and_windows
        to: "on"
        for: "00:30:00"
    action:
      - service: script.hvac_disable
      - service: notify.phones
        data_template:
          title: "Home"
          message: "HVAC disabled since a window was left open"
      - delay: "00:00:10"
      - wait_template: "{{ is_state('group.doors_and_windows', 'off') }}"
      - service: script.hvac_resume

  - alias: Climate - Away
    initial_state: True
    trigger:
      - platform: state
        entity_id: alarm_control_panel.abode_alarm
        to: "armed_away"
        for: "12:00:00"
    action:
      - service: script.hvac_disable
      - service: notify.phones
        data_template:
          title: "Home"
          message: "HVAC set to away mode"
      - delay: "00:00:10"
      - wait_template: "{{ is_state('alarm_control_panel.abode_alarm', 'disarmed') }}"
      - service: script.hvac_resume
