automation:
  - alias: Energy - Power grid status
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "on"
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "off"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "PG&E grid is {{ states('binary_sensor.grid_status') }}! Powerwall is at {{ states('sensor.powerwall_charge') }}%"

  - alias: Energy - Disable climate if power out
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "off"
    action:
      - service: climate.turn_off
        data:
          entity_id: climate.home
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Disabling HVAC – You can turn back on manually"

  - alias: Energy - UPS status change
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ups_status
    action:
      - service: notify.mobile_app_jeffs_iphone
        data_template:
          title: "Home"
          message: "UPS status change: {{ states('sensor.ups_status') }} at {{ states('sensor.ups_battery_charge') }}%"