sensor:
  - platform: template
    sensors:
      # fix data discrepancy between integration and app
      powerwall_charge_actual:
        unique_id: "powerwall_charge_actual"
        unit_of_measurement: "%"
        device_class: "battery"
        value_template: >-
          {% set value = ((states('sensor.powerwall_charge') | float(0) / 100.0) - (0.05)) / (0.95) | float(0) %}
          {{ (value * 100) | round(1) }}


utility_meter:
  energy_import:
    source: sensor.powerwall_site_import
    cycle: daily
  energy_export:
    source: sensor.powerwall_site_export
    cycle: daily


automation:
  - alias: "Energy - Power grid status"
    initial_state: True
    mode: single
    trigger:
      # Be explicit on on/off to avoid API outage notifications
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "on"
        from: "off"
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "off"
        from: "on"
    action:
      - service: notify.phones
        data_template:
          title: "Power grid is {{ trigger.to_state }}!"
          message: "Powerwall at {{ states('sensor.powerwall_charge') }}%"

  - alias: "Energy - UPS status change"
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ups_status
        to: "Online Battery Charging"
      - platform: state
        entity_id: sensor.ups_status
        to: "On Battery Battery Discharging"
    action:
      service: notify.mobile_app_jeffs_iphone
      data_template:
        title: "UPS is {{ trigger.to_state.state }}!"
        message: "Battery at {{ states('sensor.ups_battery_charge') }}%"

  - alias: "Energy - Disable climate if power out"
    initial_state: True
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.grid_status
        to: "off"
    action:
      - service: climate.turn_off
        data:
          entity_id: climate.home
      - service: notify.phones
        data_template:
          title: "Disabling HVAC"
          message: "You can turn back on manually"