homeassistant:
    customize_glob:
      "binary_sensor.garage_door_*":
        device_class: opening

cover:
  - platform: template
    covers:
        garage_door_1:
            device_class: garage
            unique_id: "garage_door_1"
            value_template: "{{ is_state('binary_sensor.garage_door_1', 'on') }}"
            open_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_1
            close_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_1
            stop_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_1

        garage_door_2:
            device_class: garage
            unique_id: "garage_door_2"
            value_template: "{{ is_state('binary_sensor.garage_door_2', 'on') }}"
            open_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_2
            close_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_2
            stop_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_2

        garage_door_3:
            device_class: garage
            unique_id: "garage_door_3"
            value_template: "{{ is_state('binary_sensor.garage_door_3', 'on') }}"
            open_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_3
            close_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_3
            stop_cover:
                service: switch.turn_on
                entity_id: switch.garage_door_3

automation:
  - alias: "Garages - Door open"
    initial_state: True
    trigger:
      platform: state
      entity_id:
        - binary_sensor.garage_door_1
        - binary_sensor.garage_door_2
        - binary_sensor.garage_door_3
      to: "on"
      for:
        minutes: 10
    mode: parallel
    actions:
      # take a picture
      - action: camera.snapshot
        data:
          entity_id: camera.driveway
          filename: "/config/www/cameras/garages.jpg"
      # send notification
      - action: notify.phones
        data_template:
          title: "Home"
          message: "{{ trigger.to_state.attributes.friendly_name }} is open"
          data:
            url: "/lovelace/outside"
            image: "/local/cameras/garages.jpg"
            actions:
              - action: "garage_close_{{ trigger.to_state.entity_id }}"
                title: "Close"

  - alias: "Garages - Fan"
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: sensor.garage_temp
        above: !secret garage_fan_above
        for:
          minutes: 10
        variables:
          action: "turn_on"
      - platform: numeric_state
        entity_id: sensor.garage_temp
        below: !secret garage_fan_below
        for:
          minutes: 10
        variables:
          action: "turn_off"
    actions:
      - action: >
          switch.{{ action }}
        entity_id: switch.garage_fan