light:
  # Overrides
  - platform: switch
    name: "Boys Bedroom"
    entity_id: switch.boys_bedroom
  - platform: switch
    name: "Kitchen Cabinets"
    entity_id: switch.kitchen_cabinets
  - platform: switch
    name: "Living Room"
    entity_id: switch.living_room
  - platform: switch
    name: "Hallway"
    entity_id: switch.hallway
  - platform: switch
    name: "Garage"
    entity_id: switch.garage_light
  - platform: switch
    name: "Front Door"
    entity_id: switch.front_yard
  - platform: switch
    name: "Back Doors"
    entity_id: switch.back_yard
  - platform: switch
    name: "Twinkle Lights"
    entity_id: switch.twinkle_lights
  - platform: switch
    name: "Pool"
    entity_id: switch.pool_light
  
  # Groups
  - platform: group
    name: "Kitchen"
    unique_id: kitchen
    entities:
      - light.kitchen_1
      - light.kitchen_2

  - platform: group
    name: "Kitchen Area"
    unique_id: kitchen_area
    entities:
      - light.kitchen
      - light.island
      - light.kitchen_cabinets
      - light.family_room

  - platform: group
    name: "Living Area"
    unique_id: living_area
    entities:
      - light.living_room
      - light.dining_room
      - light.entryway

  - platform: group
    name: "Bedroom Area"
    unique_id: bedroom_area
    entities: 
      - light.boys_bedroom
      - light.guest_bedroom
      - light.master_bedroom
      - light.play_room

  - platform: group
    name: "Outside"
    unique_id: outside
    entities:
      - light.back_doors
      - light.twinkle_lights
      - light.garage
      - light.pool

  - platform: group
    name: "House"
    unique_id: house
    entities:
      - light.outside
      - light.kitchen_area
      - light.living_area
      - light.bedroom_area
      - light.hallway

binary_sensor:
  # Groups
  - platform: group
    name: "Doors and Windows"
    device_class: door
    unique_id: doors_and_windows
    entities:
      - binary_sensor.front_door
      - binary_sensor.family_room_doors
      - binary_sensor.master_bedroom_doors
      - binary_sensor.laundry_room_door
      - binary_sensor.dining_room_window
      - binary_sensor.living_room_window_left
      - binary_sensor.living_room_window_right
      - binary_sensor.kitchen_window
      - binary_sensor.boys_window
      - binary_sensor.playroom_window
      - binary_sensor.guest_window
      - binary_sensor.master_bedroom_window
  - platform: group
    name: "Garage Doors"
    device_class: door
    unique_id: garage_doors
    entities:
      - binary_sensor.garage_door_side
      - binary_sensor.garage_door_1
      - binary_sensor.garage_door_2
      - binary_sensor.garage_door_3
  - platform: group
    name: "Doors and Windows and Garages"
    device_class: door
    unique_id: doors_and_windows_and_garages
    entities:
      - binary_sensor.garage_doors
      - binary_sensor.garage_side_door
      - binary_sensor.doors_and_windows

group:
  # making these normal groups so that more-info shows the entities
  lights_house:
    name: "Lights"
    icon: mdi:ceiling-light
    entities:
      - light.family_room
      - light.kitchen
      - light.kitchen_cabinets
      - light.island
      - light.living_room
      - light.dining_room
      - light.entryway
      - light.hallway
      - light.master_bedroom
      - light.boys_bedroom
      - light.guest_bedroom
      - light.play_room
      - light.back_doors
      - light.twinkle_lights
      - light.garage
      - light.pool
      
  media_player_speakers:
    name: "Speakers"
    entities:
      - media_player.family_room_speakers
      - media_player.garage_speakers
      - media_player.kitchen_hub
      - media_player.living_room_speakers
      - media_player.master_bedroom_speaker
      - media_player.outside_speakers
      - media_player.playroom_speakers

  media_player_tvs:
    name: "TVs"
    entities:
      - media_player.family_room_apple_tv
      - media_player.living_room_apple_tv
      - media_player.master_bedroom_apple_tv

  media_player_speakers_and_tvs:
    name: "Media"
    icon: "mdi:television"
    entities:
      - group.media_player_speakers
      - group.media_player_tvs

  garages:
    name: "Garages"
    icon: "mdi:garage"
    entities:
      - cover.garage_door_1
      - cover.garage_door_2
      - cover.garage_door_3