automation:
  - alias: Health - Low battery check
    initial_state: True
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      condition: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level|int < 20 -%}
            {{ true }}
          {%- endif -%}
        {%- endfor -%}
    action:
      - service: notify.jeffs_phone
        data_template:
          message: >
            {% for zwave in states.zwave if zwave.attributes.battery_level %}
              {%- if zwave.attributes.battery_level|int < 20 -%}
                {{ zwave.attributes.friendly_name }} sensor needs new batteries.
              {%- endif -%}
            {%- endfor -%}

  - alias: Health - Dead sensor check
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - zwave.front_landscape
          - zwave.back_landscape
          - zwave.fountain
          - zwave.doorbell
        to: "dead"
    action:
      - service: notify.jeffs_phone
        data_template:
          message: "A zwave node is marked as dead. Trying to heal: {{ trigger.to_state.attributes.friendly_name }}."
      - delay: "00:00:60"
      - service: zwave.test_node
        data_template:
          node_id: "{{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.node_id }}"
      - delay: "00:00:60"
      - condition: template
        value_template: "{{ states[trigger.to_state.domain][trigger.to_state.object_id].state == 'dead' }}"
      - service: notify.jeffs_phone
        data_template:
          message: "I could not heal the zwave node: {{ trigger.to_state.attributes.friendly_name }}."