automation:
  - alias: Landscape - Lights
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:15:00"
      # off
      - platform: time
        at: "22:00:00"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id:
          - switch.front_landscape
          - switch.back_landscape

  - alias: Landscape - Front door light
    initial_state: True
    trigger:
      # on
      - platform: time
        at: "22:00:00"
      # off
      - platform: sun
        event: sunrise
        offset: "-00:30:00"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunrise" %}off{% else %}on{% endif %}
        entity_id:
          switch.front_yard_switch

  - alias: Landscape - Fountain
    initial_state: True
    trigger:
      # on
      - platform: time
        at: "09:00:00"
      # off
      - platform: sun
        event: sunset
    action:
      - service_template: >
          {%- if trigger and trigger.event == "sunset" -%}
            switch.turn_off
          {%- elif states.sensor.outdoor_forecast.state|lower|regex_search('wind|rain') -%}
            switch.turn_off
          {%- else -%}
            switch.turn_on
          {%- endif -%}
        entity_id:
          switch.fountain

  - alias: Landscape - Back door light
    initial_state: True
    trigger:
      - platform: state
        entity_id: binary_sensor.family_room_doors
        to: "on"
      - platform: state
        entity_id: binary_sensor.master_bedroom_doors
        to: "on"
    condition:
      condition: template
      value_template: '{{ state_attr("sun.sun", "elevation") < -4 }}'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.back_yard_switch