automation:
  - alias: "Landscape - Lighting"
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:15:00"
        variables:
          action: "turn_on"
      # off
      - platform: time
        at: "23:00:00"
        variables:
          action: "turn_off"
    actions:
      - action: >
          switch.{{ action }}
        entity_id:
          - switch.front_landscape
          - switch.back_landscape

  - alias: "Landscape - Fountain"
    initial_state: True
    trigger:
      # on
      - platform: time
        at: "08:00:00"
        variables:
          action: "turn_on"
      # off
      - platform: sun
        event: sunset
        variables:
          action: "turn_off"
    actions:
      - action: >
          switch.{{ action }}
        entity_id:
          switch.fountain

  - alias: "Landscape - Automatic front lights"
    initial_state: True
    trigger:
      # time on
      - platform: time
        at: "22:00:00"
        variables:
          action: "turn_on"
      # time off
      - platform: sun
        event: sunrise
        offset: "-00:30:00"
        variables:
          action: "turn_off"
      # doorbell
      - platform: webhook
        webhook_id: "camera_doorbell"
        local_only: True
        variables:
          action: "turn_off"
      # door opened
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < -4 }}'
    actions:
      - action: >
          light.{{ action }}
        entity_id:
          light.front_door

  - alias: "Landscape - Automatic back lights"
    initial_state: True
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.family_room_doors
          - binary_sensor.master_bedroom_doors
        to: "on"
    condition:
      - condition: template
        value_template: '{{ state_attr("sun.sun", "elevation") < -4 }}'
      - condition: state
        entity_id: light.twinkle_lights
        state: "off"
    actions:
      - action: light.turn_on
        entity_id: light.back_doors
