light:
  - platform: group
    name: Kitchen
    entities:
      # node 7
      - light.kitchen_1
      # node 6
      - light.kitchen_2


group:
  landscape_lights:
    entities:
      # node 32
      - switch.back_landscape
      # node 31
      - switch.front_landscape
      # node 45
      - switch.front_yard_switch
      # node 39
      - switch.pool_light
  bedroom_lights:
    entities:
      # node 35
      - switch.boys_bedroom
      # node 26
      - light.guest_bedroom
      # node 27
      - light.master_bedroom
      # node 41
      - light.play_room
  kitchen_lights:
    entities:
      - light.Kitchen
      # node 5
      - light.island
      # node 16
      - switch.kitchen_cabinets
      # node 3
      - light.pantry
  lights:
    entities:
      - group.bedroom_lights
      - group.kitchen_lights
      # node 8
      - light.family_room
      # node 34
      - light.dining_room
      # node 10
      - switch.living_room
      # node 14
      - switch.entryway
      # node 15
      - switch.hallway
      # node 9
      - switch.back_yard_switch


automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "22:00:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.abode_alarm
      state: "armed_away"
    action:
      - delay: "00:{{ (range(1, 30)|random|int) }}:{{ (range(1, 59)|random|int) }}"
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room
      - service: notify.slack
        data_template:
          message: Turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway
      - service: tts.google_say
        entity_id: "all"
        data_template:
          message: "Welcome home. I turned the lights on for you."

  - alias: Lights - Turn off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "09:00:00"
    condition:
      condition: state
      entity_id: group.lights
      state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.lights