automation:
  - alias: "Lights - Toggle when away"
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        variables:
          action: "turn_on"
      # off
      - platform: time
        at: "22:00:00"
        variables:
          action: "turn_off"
    condition:
      condition: state
      entity_id: alarm_control_panel.alarm
      state: "armed_away"
    action:
      # randomize the time the light turns on
      - delay: "00:{{ (range(1, 30)|random|int) }}:{{ (range(1, 59)|random|int) }}"
      # edge case: Check the alarm is still on after the delay is up
      - if:
          condition: state
          entity_id: alarm_control_panel.alarm
          state: "armed_away"
        then:
          - service: >
              light.{{ action }}
            entity_id: light.living_room
          - service: notify.phones
            data_template:
              title: "Home"
              message: "Turning the lights {% if action == 'turn_on' %}on while you are away{% else %}off{% endif %}"

  - alias: "Lights - Turn on when coming home"
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: light.turn_on
        entity_id: light.hallway
      - service: notify.house
        data_template:
          message: "Welcome home I turned the lights on for you"

  - alias: "Lights - Turn off after sunrise"
    initial_state: True
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: state
      entity_id: light.house
      state: "on"
    action:
      - service: light.turn_off
        entity_id: light.house

  - alias: "Lights - Twinkle lights"
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
        offset: "00:00:00"
        variables:
          action: "turn_on"
      # off
      - platform: time
        at: "21:30:00"
        variables:
          action: "turn_off"
    condition:
      - condition: state
        entity_id: alarm_control_panel.alarm
        state: "disarmed"
    action:
      - service_template: >
          homeassistant.{{ action }}
        entity_id: light.twinkle_lights

  - alias: "Lights - Reset dim level to full"
    initial_state: True
    trigger:
      - platform: state
        entity_id: 
          - light.master_bedroom
        to: "on"
    condition:
      # only trigger when switch is manually turned on
      condition: template
      value_template: "{{ trigger.to_state.context.user_id == None }}"
    action:
      - service: light.turn_on
        target:
          entity_id: "{{ trigger.entity_id }}"
        data:
          brightness: 255
          transition: 3

  - alias: "Lights - Playroom light toggles bulb"
    initial_state: True
    trigger:
      # on
      - platform: state
        entity_id: light.play_room
        to: "on"
        variables:
          action: "turn_on"
      # off
      - platform: state
        entity_id: light.play_room
        to: "off"
        variables:
          action: "turn_off"
    action:
      - service: >
          light.{{ action }}
        entity_id: light.zipato_bulb