light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_1
      - light.kitchen_2


group:
  landscape_lights:
    entities:
      - switch.back_landscape
      - switch.front_landscape
      - switch.front_yard_switch
      - switch.pool_light
  bedroom_lights:
    entities:
      - switch.boys_bedroom
      - light.guest_bedroom
      - light.master_bedroom
      - light.play_room
  kitchen_lights:
    entities:
      - light.Kitchen
      - light.island
      - switch.kitchen_cabinets
      - light.pantry
  lights:
    entities:
      - group.bedroom_lights
      - group.kitchen_lights
      - light.family_room
      - light.dining_room
      - switch.living_room
      - light.entryway
      - switch.hallway
      - switch.back_yard_switch


automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "22:00:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.abode_alarm
      state: "armed_away"
    action:
      - delay: "00:{{ (range(1, 30)|random|int) }}:{{ (range(1, 59)|random|int) }}"
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room
      - service: notify.slack
        data_template:
          message: Turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway
      - service: tts.google_say
        entity_id: "all"
        data_template:
          message: "Welcome home. I turned the lights on for you."

  - alias: Lights - Turn off after sunrise
    initial_state: True
    trigger:
      platform: time
      at: "08:00:00"
    condition:
      condition: state
      entity_id: group.lights
      state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.lights

  - alias: Lights - Playroom light toggles bulb
    initial_state: True
    trigger:
      - platform: state
        entity_id: light.play_room
        to: "on"
      - platform: state
        entity_id: light.play_room
        to: "off"
    action:
      - service_template: >
          light.turn_{% if trigger and trigger.to_state.state == "on" %}on{% else %}off{% endif %}
        entity_id: light.zipato_bulb