light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_1
      - light.kitchen_2


group:
    lights:
      entities:
        - light.family_room
        - light.island
        - light.Kitchen
        - switch.kitchen_cabinets
        - light.pantry
        - light.dining_room
        - switch.living_room
        - switch.entryway
        - switch.hallway
        - switch.boys_bedroom
        - light.guest_bedroom
        - light.play_room
        - light.master_bedroom
        - switch.back_yard_switch


automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "23:03:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.abode_alarm
      state: "armed_away"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Home Assistant
          message: Turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.abode_alarm
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway
      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target:
            - media_player.master_bedroom_echo
            - media_player.living_room_echo
            - media_player.family_room_echo
          message: "Welcome home. I turned the lights on for you."

  - alias: Lights - Turn off after sunrise
    initial_state: True
    trigger:
      platform: sun
      event: sunrise
      offset: '+01:00:00'
    condition:
      condition: state
      entity_id: group.lights
      state: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.lights