light:
  - platform: group
    name: Kitchen
    entities:
      - light.kitchen_lights_1_level
      - light.kitchen_lights_2_level


group:
    lights:
      entities:
        - light.family_room_lights_level
        - light.island_lights_level
        - light.Kitchen
        - switch.kitchen_cabinets_switch
        - light.pantry_light_level
        - light.dining_room_lights_level
        - switch.living_room_switch
        - switch.entryway_light_switch
        - switch.hallway_light_switch
        - switch.guest_room_switch
        - light.masons_room_level
        - light.master_bedroom_level


automation:
  - alias: Lights - Toggle when away
    initial_state: True
    trigger:
      # on
      - platform: sun
        event: sunset
      # off
      - platform: time
        at: "23:03:00"
    condition:
      condition: state
      entity_id: alarm_control_panel.alarm
      state: "armed_away"
    action:
      - service_template: >
          switch.turn_{% if trigger and trigger.event == "sunset" %}on{% else %}off{% endif %}
        entity_id: switch.living_room_switch
      - service: notify.jeff_and_jillians_phone
        data_template:
          title: Home Assistant
          message: Turning the lights {% if trigger and trigger.event == "sunset" %}on while you are away{% else %}off{% endif %}.

  - alias: Lights - Turn on when coming home
    initial_state: True
    trigger:
      platform: state
      entity_id: alarm_control_panel.alarm
      from: "armed_away"
      to: "disarmed"
    condition:
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - switch.hallway_light_switch
      - service: media_player.alexa_tts
        data_template:
          entity_id: media_player.master_bedroom
          message: Welcome home. I turned the lights on for you.