
remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_url


input_select:
  family_room_media:
    name: "Input"
    options:
      - "Select One"
      - "Power Off"
      - "Apple TV"
      - "Chromecast"
      - "Speakers"
      - "Bluetooth"
    initial: "Select One"


sensor:
  - platform: template
    sensors:
      family_room_media:
        value_template: "{{ state_attr('remote.family_room', 'current_activity')|replace('PowerOff', 'Off') }}"


automation:
  - alias: Media - Input acts as remote
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.family_room_media
    action:
      - service: remote.turn_on
        data_template:
          entity_id: remote.family_room
          activity: >
            {% if is_state("input_select.family_room_media", "Apple TV") %}
              21762413
            {% elif is_state("input_select.family_room_media", "Chromecast") %}
              47442815
            {% elif is_state("input_select.family_room_media", "Speakers") %}
              18890244
            {% elif is_state("input_select.family_room_media", "Bluetooth") %}
              22068322
            {% elif is_state("input_select.family_room_media", "Power Off") %}
              -1
            {% endif %}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.family_room_media
          option: "Select One"
