remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_url


input_select:
  family_room_media:
    name: Input
    options:
      - Select
      - Power Off
      - Apple TV
      - Fire TV
      - Speakers
      - Bluetooth
    initial: Select


sensor:
  - platform: template
    sensors:
      family_room_media:
        value_template: "{{ states.remote.family_room.attributes.current_activity|replace('PowerOff', 'Off') }}"


automation:
  - alias: Media - Input acts as remote
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_select.family_room_media
    action:
      - service: remote.turn_on
        data_template:
          entity_id: remote.family_room
          activity: >
            {% if states.input_select.family_room_media.state == "Apple TV" %}
              21762413
            {% elif states.input_select.family_room_media.state == "Fire TV" %}
              35169619
            {% elif states.input_select.family_room_media.state == "Speakers" %}
              18890244
            {% elif states.input_select.family_room_media.state == "Bluetooth" %}
              22068322
            {% elif states.input_select.family_room_media.state == "Power Off" %}
              -1
            {% endif %}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.family_room_media
          option: Select
