group:
  Media:
    entities:
      - sensor.family_room_media
      - input_select.family_room_media


remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_host


input_select:
  family_room_media:
    name: Input
    options:
      - Select
      - Power Off
      - Apple TV
      - DVD Player
      - Music
      - Bluetooth
    initial: Select


sensor:
  - platform: template
    sensors:
      family_room_media:
        friendly_name: Family Room
        value_template: '{{ states.remote.family_room.attributes.current_activity }}'
        icon_template: mdi:television


homeassistant:
  customize:
    input_select.family_room_media:
      icon: mdi:remote


automation:
  - alias: Media input changes trigger remote
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: input_select.family_room_media
    action:
      - service: remote.turn_on
        data_template:
          entity_id: remote.family_room
          activity: >
            {% if states.input_select.family_room_media.state == 'Apple TV' %}
              21762413
            {% elif states.input_select.family_room_media.state == 'DVD Player' %}
              21762603
            {% elif states.input_select.family_room_media.state == 'Music' %}
              18890244
            {% elif states.input_select.family_room_media.state == 'Bluetooth' %}
              22068322
            {% elif states.input_select.family_room_media.state == 'Power Off' %}
              -1
            {% endif %}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.family_room_media
          option: Select