google_assistant:
  project_id: !secret google_assistant_id
  service_account: !include ../google_assistant_key.json
  report_state: true
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - script
    - scene
  entity_config:
    scene.good_morning:
      expose: false
    scene.let_dog_out:
      expose: false
    light.kitchen_1:
      expose: false
    light.kitchen_2:
      expose: false
    switch.front_landscape:
      expose: false
    switch.back_landscape:
      expose: false
    switch.fountain:
      expose: false
    sensor.washer_power:
      expose: false
    script.snapshot_door_and_send:
      expose: false
    script.snapshot_cameras_and_send:
      expose: false
    script.alarm_disarm_silently:
      expose: false
    script.good_morning:
      expose: false
    script.hvac_windows_open:
      expose: false
    script.hvac_windows_closed:
      expose: false


remote:
  - platform: harmony
    name: Family Room
    host: !secret harmony_url


input_select:
  family_room_media:
    name: "Input"
    options:
      - "Select One"
      - "Power Off"
      - "Apple TV"
      - "Fire TV"
      - "Speakers"
      - "Speakers Outside"
      - "Bluetooth"
    initial: "Select One"


sensor:
  - platform: template
    sensors:
      family_room_media:
        value_template: "{{ state_attr('remote.family_room', 'current_activity')|replace('PowerOff', 'Off') }}"


automation:
  - alias: Media - Input acts as remote
    initial_state: True
    trigger:
      platform: state
      entity_id: input_select.family_room_media
    action:
      - service: remote.turn_on
        data_template:
          entity_id: remote.family_room
          activity: >
            {% if is_state("input_select.family_room_media", "Apple TV") %}
              21762413
            {% elif is_state("input_select.family_room_media", "Fire TV") %}
              35169619
            {% elif is_state("input_select.family_room_media", "Speakers") %}
              18890244
            {% elif is_state("input_select.family_room_media", "Speakers Outside") %}
              44120137
            {% elif is_state("input_select.family_room_media", "Bluetooth") %}
              22068322
            {% elif is_state("input_select.family_room_media", "Power Off") %}
              -1
            {% endif %}
      - service: input_select.select_option
        data_template:
          entity_id: input_select.family_room_media
          option: "Select One"
