binary_sensor:
  - platform: ping
    name: internet
    host: 8.8.8.8
    scan_interval: 300

  - platform: ping
    name: living_room_camera
    host: !secret living_room_camera_url
    scan_interval: 300

  - platform: ping
    name: family_room_camera
    host: !secret family_room_camera_url
    scan_interval: 300

  - platform: ping
    name: front_yard_camera
    host: !secret front_yard_camera_url
    scan_interval: 300

  - platform: ping
    name: back_yard_camera
    host: !secret back_yard_camera_url
    scan_interval: 300

  - platform: ping
    name: awair
    host: !secret awair_url
    scan_interval: 300

  - platform: ping
    name: harmony_hub
    host: !secret harmony_url
    scan_interval: 300

  - platform: ping
    name: skybell
    host: !secret skybell_url
    scan_interval: 300

  - platform: ping
    name: abode_gateway
    host: !secret abobe_gateway_url
    scan_interval: 300

  - platform: ping
    name: ambient_observer
    host: !secret ambient_observer_url
    scan_interval: 300


automation:
  - alias: Network - Offline Devices
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.living_room_camera
          - binary_sensor.family_room_camera
          - binary_sensor.front_yard_camera
          - binary_sensor.back_yard_camera
          - binary_sensor.awair
          - binary_sensor.harmony_hub
          - binary_sensor.skybell
          - binary_sensor.abode_gateway
          - binary_sensor.ambient_observer
        to: "off"
    action:
      - service: notify.jeffs_phone
        data_template:
          message: "{{ trigger.to_state.attributes.friendly_name }} is offline"