shell_command:
  purge_backups: "find ./backups -maxdepth 1 -name '*.tar' -type f -mtime +365 -delete"

input_boolean:
  guest_mode:
    name: "Guest Mode"
    initial: "off"
    icon: "mdi:bed"

automation:
  - alias: System - Backup
    initial_state: True
    trigger:
      platform: time
      at: "01:00:00"
    condition:
      condition: template
      value_template: "{{ now().day == 1 }}"
    action:
      - service: backup.create
      - service: shell_command.purge_backups

  - alias: System - Theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: System - Settings reset each day
    initial_state: True
    trigger:
      platform: time
      at: "04:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.cameras_doorbell
          - automation.cameras_doorbell_motion
          - automation.cameras_mailbox_open
          - automation.alarm_status_home
          - automation.alarm_status_disarmed
          - automation.garages_door_open
          - automation.landscape_fountain
          - automation.landscape_back_door_light

  - alias: System - Reset speaker volumes
    initial_state: True
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: media_player.volume_set
        target:
          entity_id: media_player.kitchen_display
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speakers
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.master_bedroom_speaker
        data:
          volume_level: 0.5

  - alias: System - Refresh non-zwave plus nodes
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/5"
    action:
      - service: zwave_js.refresh_value
        data:
          entity_id:
            - light.family_room
            - light.entryway
            - light.island
            - light.kitchen_1
            - light.kitchen_2
            - light.master_bedroom
            - light.pantry
            - switch.hallway
            - switch.kitchen_cabinets
            - switch.living_room
          refresh_all_values: false

  - alias: System - Node health check
    initial_state: True
    trigger:
      platform: time
      at: "20:00:00"
      variables:
         unavailable_nodes: "{{ states | selectattr('state', 'in', 'dead, unavailable') }}"
    condition:
      condition: template
      value_template: "{{ unavailable_nodes }}"
    action:
      - service: notify.mobile_app_jeffs_iphone
        data_template:
          message: "The following are unavailable: {{ unavailable_nodes | map(attribute='name') | join(', ') }}"

