tts:
  - platform: google_cloud
    service_name: google_say
    key_file: google_cloud_key.json
    base_url: !secret external_url
    voice: en-US-Wavenet-C
    text_type: ssml
    speed: 1.1
    pitch: 4.0
    cache: false
    profiles:
      - medium-bluetooth-speaker-class-device


automation:
  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  # - alias: System - Low battery check
  #   initial_state: True
  #   trigger:
  #     platform: time
  #     at: "00:00:00"
  #   condition:
  #     condition: template
  #     value_template: >
  #       {% for battery in states.sensor if battery.attributes.device_class == 'battery' %}
  #         {%- if (battery.state|int(0) < 100) -%}
  #           {{ true }}
  #         {% endif %}
  #       {% endfor %}
  #   action:
  #     - service: notify.phones
  #       data_template:
  #         title: "Home"
  #         message: >
  #           Warning!
  #           {% for battery in states.sensor if battery.attributes.device_class == 'battery' %}
  #             {%- if (battery.state|int(0) < 100) -%}
  #               - {{ battery.attributes.friendly_name }} battery is low.
  #             {% endif %}
  #           {% endfor %}

  - alias: System - Reset speaker volumes
    initial_state: True
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: media_player.volume_set
        target:
          entity_id: media_player.kitchen_display
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.master_bedroom_speaker
        data:
          volume_level: 0.5

  - alias: System - Refresh non-zwave plus nodes
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/5"
    action:
      - service: zwave_js.refresh_value
        data:
          entity_id:
            - light.family_room
            - light.entryway
            - light.island
            - light.kitchen_1
            - light.kitchen_2
            - light.master_bedroom
            - light.pantry
            - switch.hallway
            - switch.kitchen_cabinets
            - switch.living_room
          refresh_all_values: false