input_boolean:
  guest_mode_enabled:
    name: "Guest Mode"
    icon: "mdi:bed"

automation:
  - alias: "System - Theme change"
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: "System - Reset settings"
    initial_state: True
    trigger:
      platform: time
      at: "04:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.cameras_doorbell
          - automation.cameras_mailbox_open
          - automation.climate_windows_open
          - automation.landscape_fountain
          - automation.landscape_back_door_light
          - input_boolean.camera_motion_enabled

  - alias: "System - Reset speakers"
    initial_state: True
    trigger:
      platform: time
      at: "12:00:00"
    action:
      - service: media_player.volume_set
        target:
          entity_id: 
            - media_player.kitchen_hub
            - media_player.living_room_speakers
            - media_player.playroom_speakers
        data:
          volume_level: 0.6
      # some speakers should be quieter
      - service: media_player.volume_set
        target:
          entity_id: media_player.master_bedroom_speaker
        data:
          volume_level: 0.5

  - alias: "System - Refresh non-zwave plus nodes"
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/5"
    action:
      - service: zwave_js.refresh_value
        data:
          entity_id:
            - light.family_room
            - light.entryway
            - light.island
            - light.kitchen_1
            - light.kitchen_2
            - light.master_bedroom
            - light.pantry
            - light.play_room
            - switch.hallway
            - switch.kitchen_cabinets
            - switch.living_room
            - switch.back_yard
            - switch.house_fan
          refresh_all_values: false

  # Disabled by default
  - alias: "System - Entity health check"
    initial_state: False
    trigger:
      platform: time
      at: "04:00:00"
      variables:
         unhealthy: "{{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'dead', 'none']) | list | map(attribute='name') | join(', ') }}"
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - if:
          condition: template
          value_template: "{{ unhealthy | length > 0 }}"
        then:
          service: persistent_notification.create
          data:
            notification_id: unhealthy
            message: "The following are unavailable: {{ unhealthy }}"