tts:
  - platform: google_cloud
    key_file: google_cloud_key.json
    base_url: !secret external_url
    voice: en-US-Standard-J
    text_type: ssml
    cache: false
    service_name: google_say


automation:
  - alias: System - UI theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: System - UI home image
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/2"
    action:
      - service: script.turn_on
        entity_id: script.snapshot_door_and_save

  - alias: System - Low battery check
    initial_state: True
    trigger:
      platform: time
      at: "00:00:00"
    condition:
      condition: template
      value_template: >
        {% for zwave in states.zwave if zwave.attributes.battery_level %}
          {%- if zwave.attributes.battery_level|int < 20 -%}
            {{ true }}
          {%- endif -%}
        {%- endfor -%}
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Home
          message: >
            {% for zwave in states.zwave if zwave.attributes.battery_level %}
              {%- if zwave.attributes.battery_level|int < 20 -%}
                {{ zwave.attributes.friendly_name }} needs new batteries.
              {%- endif -%}
            {%- endfor -%}

  - alias: System - Dead sensor check
    initial_state: True
    trigger:
      - platform: state
        entity_id:
          - zwave.front_landscape
          - zwave.back_landscape
          - zwave.fountain
          - zwave.doorbell
          - zwave.pool_light
        to: "dead"
    action:
      - service: notify.jeffs_phone
        data_template:
          title: Home
          message: "{{ trigger.to_state.attributes.friendly_name }} is dead. Let me heal it..."
      - delay: "00:00:60"
      - service: zwave.test_node
        data_template:
          node_id: "{{ states[trigger.to_state.domain][trigger.to_state.object_id].attributes.node_id }}"
      - delay: "00:00:60"
      - condition: template
        value_template: "{{ states[trigger.to_state.domain][trigger.to_state.object_id].state == 'dead' }}"
      - service: notify.jeffs_phone
        data_template:
          title: Home
          message: "No luck. {{ trigger.to_state.attributes.friendly_name }} is marked as dead."