automation:
  - alias: System - Theme change
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data_template:
        name: home

  - alias: System - Settings reset each day
    initial_state: True
    trigger:
      platform: time
      at: "04:00:00"
    action:
      - service: homeassistant.turn_on
        entity_id:
          - automation.security_doorbell_notifications
          - automation.security_mailbox_open
          - automation.security_status_alerts
          - automation.security_garage_door_open
          - automation.landscape_back_door_light

  - alias: System - Reset speaker volumes
    initial_state: True
    trigger:
      platform: time
      at: "06:00:00"
    action:
      - service: media_player.volume_set
        target:
          entity_id: media_player.kitchen_display
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.living_room_speaker
        data:
          volume_level: 0.6
      - service: media_player.volume_set
        target:
          entity_id: media_player.master_bedroom_speaker
        data:
          volume_level: 0.5

  - alias: System - Refresh non-zwave plus nodes
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/5"
    action:
      - service: zwave_js.refresh_value
        data:
          entity_id:
            - light.family_room
            - light.entryway
            - light.island
            - light.kitchen_1
            - light.kitchen_2
            - light.master_bedroom
            - light.pantry
            - switch.hallway
            - switch.kitchen_cabinets
            - switch.living_room
          refresh_all_values: false

  - alias: System - Node health check
    initial_state: True
    trigger:
      platform: time
      at: "20:00:00"
      variables:
         unavailable_nodes: "{{ states | selectattr('state', 'in', 'dead, unavailable') }}"
    condition:
      condition: template
      value_template: "{{ unavailable_nodes }}"
    action:
      - service: notify.mobile_app_jeffs_iphone
        data_template:
          message: "The following are unavailable: {{ unavailable_nodes | map(attribute='name') | join(', ') }}"

