sun:

shell_command:
  cache_weather: !secret cache_weather_cmd

sensor:
  - platform: template
    sensors:
      outside_forecast:
        value_template: >
          {{ states("weather.krhv_daynight")|replace("-", " ")|replace("partlycloudy", "partly cloudy")|default("") }}
        icon_template: >
          {% set condition = states("weather.krhv_daynight") %}

          {%- if "cloud" in condition -%}
            mdi:weather-cloudy
          {%- elif "fog" in condition -%}
            mdi:weather-fog
          {%- elif "rain" in condition -%}
            mdi:umbrella-outline
          {%- elif "wind" in condition -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}


automation:
  - alias: Weather - Cache Local
    initial_state: True
    trigger:
      platform: time_pattern
      minutes: "/5"
    action:
      - service: shell_command.cache_weather
      
  - alias: Weather - Low Battery
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.outside_battery
        to: "- -"
        for: "01:00:00"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "The outside weather sensor battery is low!"
