sun:

sensor:
  - platform: template
    sensors:
      outdoor_forecast:
        value_template: >
          {% set forecast = state_attr('weather.krhv_daynight', 'forecast')[0]|default('') %}

          {{ forecast.detailed_description.split('.')[0]|lower }}
        icon_template: >
          {% set weather = state_attr('weather.krhv_daynight', 'forecast')[0].condition %}
          
          {%- if "cloud" in weather -%}
            mdi:weather-cloudy
          {%- elif "fog" in weather -%}
            mdi:weather-fog
          {%- elif "rain" in weather -%}
            mdi:umbrella-outline
          {%- elif "wind" in weather -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}


automation:
  - alias: Weather - Low Battery
    initial_state: True
    trigger:
      - platform: state
        entity_id: sensor.outside_battery
        to: "- -"
        for: "01:00:00"
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "The outside weather sensor battery is low!"
