sun:

shell_command:
  get_weather: !secret get_weather_cmd

template:
  - sensor:
    - name: outside_forecast
      icon:  >
        {% set condition = states("weather.krhv_daynight") %}

        {%- if "cloud" in condition -%}
          mdi:weather-cloudy
        {%- elif "fog" in condition -%}
          mdi:weather-fog
        {%- elif "rain" in condition -%}
          mdi:umbrella-outline
        {%- elif "wind" in condition -%}
          mdi:weather-windy
        {%- else -%}
          mdi:weather-sunny
        {%- endif %}
      state: >
        {{ 
          states("weather.krhv_daynight")
          |replace("-", " ")
          |replace("partlycloudy", "partly cloudy")
          |replace("unknown", "")
        }}

automation:
  - alias: "Weather - Cache Local"
    trigger:
      platform: time_pattern
      minutes: "/5"
    actions:
      - action: shell_command.get_weather
