sensor:
  - platform: scrape
    name: outside_temp
    unit_of_measurement: "°F"
    resource: !secret ambient_weather_url
    select: "[name='outTemp']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_humidity
    unit_of_measurement: "%"
    resource: !secret ambient_weather_url
    select: "[name='outHumi']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_wind_speed
    unit_of_measurement: "mph"
    resource: !secret ambient_weather_url
    select: "[name='avgwind']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_wind_gust
    unit_of_measurement: "mph"
    resource: !secret ambient_weather_url
    select: "[name='gustspeed']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_uv
    unit_of_measurement: "UV Index"
    resource: !secret ambient_weather_url
    select: "[name='uvi']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_rain_daily
    unit_of_measurement: "In"
    resource: !secret ambient_weather_url
    select: "[name='rainofdaily']"
    attribute: value
    scan_interval: 300

  - platform: scrape
    name: outside_pm25
    unit_of_measurement: "µg/m3"
    resource: !secret ambient_weather_url
    select: "[name='pm25out']"
    attribute: value
    scan_interval: 300

  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    monitored_conditions:
      - hourly_summary
      - temperature_low

  - platform: template
    sensors:
      outdoor_forecast:
        value_template: "{{ states('sensor.dark_sky_hourly_summary')|default('') }}"
        icon_template: >
          {%- if "cloud" in states('sensor.dark_sky_hourly_summary')|lower -%}
            mdi:weather-cloudy
          {%- elif "fog" in states('sensor.dark_sky_hourly_summary')|lower -%}
            mdi:weather-fog
          {%- elif "rain" in states('sensor.dark_sky_hourly_summary')|lower -%}
            mdi:umbrella-outline
          {%- elif "wind" in states('sensor.dark_sky_hourly_summary')|lower -%}
            mdi:weather-windy
          {%- else -%}
            mdi:weather-sunny
          {%- endif %}


automation:
  - alias: Weather - Freezing temperature
    initial_state: True
    trigger:
      platform: numeric_state
      entity_id: sensor.dark_sky_overnight_low_temperature_0d
      below: 33
    action:
      - service: notify.phones
        data_template:
          title: "Home"
          message: "Cover the plants! Todays low temperature is {{ states('sensor.dark_sky_overnight_low_temperature_0d') }}°F."
